// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: gamenode.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 节点静态状态
type GameNodeStaticState int32

const (
	GameNodeStaticState_NODE_STATE_NORMAL      GameNodeStaticState = 0 // 正常状态
	GameNodeStaticState_NODE_STATE_MAINTENANCE GameNodeStaticState = 1 // 维护状态
	GameNodeStaticState_NODE_STATE_DISABLED    GameNodeStaticState = 2 // 禁用状态
)

// Enum value maps for GameNodeStaticState.
var (
	GameNodeStaticState_name = map[int32]string{
		0: "NODE_STATE_NORMAL",
		1: "NODE_STATE_MAINTENANCE",
		2: "NODE_STATE_DISABLED",
	}
	GameNodeStaticState_value = map[string]int32{
		"NODE_STATE_NORMAL":      0,
		"NODE_STATE_MAINTENANCE": 1,
		"NODE_STATE_DISABLED":    2,
	}
)

func (x GameNodeStaticState) Enum() *GameNodeStaticState {
	p := new(GameNodeStaticState)
	*p = x
	return p
}

func (x GameNodeStaticState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameNodeStaticState) Descriptor() protoreflect.EnumDescriptor {
	return file_gamenode_proto_enumTypes[0].Descriptor()
}

func (GameNodeStaticState) Type() protoreflect.EnumType {
	return &file_gamenode_proto_enumTypes[0]
}

func (x GameNodeStaticState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameNodeStaticState.Descriptor instead.
func (GameNodeStaticState) EnumDescriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{0}
}

// 节点注册
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // 此处仍使用string，而不是枚举，避免兼容性问题
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Hardware      map[string]string      `protobuf:"bytes,6,rep,name=hardware,proto3" json:"hardware,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	System        map[string]string      `protobuf:"bytes,7,rep,name=system,proto3" json:"system,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gamenode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *RegisterRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RegisterRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisterRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RegisterRequest) GetHardware() map[string]string {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *RegisterRequest) GetSystem() map[string]string {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	State         GameNodeStaticState    `protobuf:"varint,3,opt,name=state,proto3,enum=gamenode.GameNodeStaticState" json:"state,omitempty"` // 节点静态状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_gamenode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetState() GameNodeStaticState {
	if x != nil {
		return x.State
	}
	return GameNodeStaticState_NODE_STATE_NORMAL
}

// 心跳
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_gamenode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_gamenode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 节点指标报告
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       *MetricsInfo           `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_gamenode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsRequest) GetMetrics() *MetricsInfo {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpus          []*CPUMetrics          `protobuf:"bytes,1,rep,name=cpus,proto3" json:"cpus,omitempty"`
	Memory        *MemoryMetrics         `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpus          []*GPUMetrics          `protobuf:"bytes,3,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Storages      []*StorageMetrics      `protobuf:"bytes,4,rep,name=storages,proto3" json:"storages,omitempty"`
	Network       *NetworkMetrics        `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsInfo) Reset() {
	*x = MetricsInfo{}
	mi := &file_gamenode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsInfo) ProtoMessage() {}

func (x *MetricsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsInfo.ProtoReflect.Descriptor instead.
func (*MetricsInfo) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{5}
}

func (x *MetricsInfo) GetCpus() []*CPUMetrics {
	if x != nil {
		return x.Cpus
	}
	return nil
}

func (x *MetricsInfo) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *MetricsInfo) GetGpus() []*GPUMetrics {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *MetricsInfo) GetStorages() []*StorageMetrics {
	if x != nil {
		return x.Storages
	}
	return nil
}

func (x *MetricsInfo) GetNetwork() *NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

type CPUMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads       int32                  `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`
	Usage         float64                `protobuf:"fixed64,4,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUMetrics) Reset() {
	*x = CPUMetrics{}
	mi := &file_gamenode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUMetrics) ProtoMessage() {}

func (x *CPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUMetrics.ProtoReflect.Descriptor instead.
func (*CPUMetrics) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{6}
}

func (x *CPUMetrics) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CPUMetrics) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPUMetrics) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *CPUMetrics) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

type MemoryMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Available     int64                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Used          int64                  `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Usage         float64                `protobuf:"fixed64,4,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_gamenode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{7}
}

func (x *MemoryMetrics) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryMetrics) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *MemoryMetrics) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemoryMetrics) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

type GPUMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	MemoryTotal   int64                  `protobuf:"varint,2,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	Usage         float64                `protobuf:"fixed64,3,opt,name=usage,proto3" json:"usage,omitempty"`
	MemoryUsed    int64                  `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	MemoryFree    int64                  `protobuf:"varint,5,opt,name=memory_free,json=memoryFree,proto3" json:"memory_free,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,6,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUMetrics) Reset() {
	*x = GPUMetrics{}
	mi := &file_gamenode_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMetrics) ProtoMessage() {}

func (x *GPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMetrics.ProtoReflect.Descriptor instead.
func (*GPUMetrics) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{8}
}

func (x *GPUMetrics) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUMetrics) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *GPUMetrics) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *GPUMetrics) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *GPUMetrics) GetMemoryFree() int64 {
	if x != nil {
		return x.MemoryFree
	}
	return 0
}

func (x *GPUMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

type StorageMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Capacity      int64                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Used          int64                  `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	Free          int64                  `protobuf:"varint,6,opt,name=free,proto3" json:"free,omitempty"`
	Usage         float64                `protobuf:"fixed64,7,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageMetrics) Reset() {
	*x = StorageMetrics{}
	mi := &file_gamenode_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageMetrics) ProtoMessage() {}

func (x *StorageMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageMetrics.ProtoReflect.Descriptor instead.
func (*StorageMetrics) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{9}
}

func (x *StorageMetrics) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StorageMetrics) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StorageMetrics) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StorageMetrics) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StorageMetrics) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *StorageMetrics) GetFree() int64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *StorageMetrics) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

type NetworkMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InboundTraffic  float64                `protobuf:"fixed64,1,opt,name=inbound_traffic,json=inboundTraffic,proto3" json:"inbound_traffic,omitempty"`
	OutboundTraffic float64                `protobuf:"fixed64,2,opt,name=outbound_traffic,json=outboundTraffic,proto3" json:"outbound_traffic,omitempty"`
	Connections     int32                  `protobuf:"varint,3,opt,name=connections,proto3" json:"connections,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_gamenode_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkMetrics) GetInboundTraffic() float64 {
	if x != nil {
		return x.InboundTraffic
	}
	return 0
}

func (x *NetworkMetrics) GetOutboundTraffic() float64 {
	if x != nil {
		return x.OutboundTraffic
	}
	return 0
}

func (x *NetworkMetrics) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_gamenode_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{11}
}

func (x *MetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 资源信息更新
type ResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hardware      *HardwareInfo          `protobuf:"bytes,3,opt,name=hardware,proto3" json:"hardware,omitempty"`
	System        *SystemInfo            `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_gamenode_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{12}
}

func (x *ResourceRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ResourceRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ResourceRequest) GetHardware() *HardwareInfo {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *ResourceRequest) GetSystem() *SystemInfo {
	if x != nil {
		return x.System
	}
	return nil
}

type ResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	mi := &file_gamenode_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResourceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 状态变更请求
type StateChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TargetState   GameNodeStaticState    `protobuf:"varint,2,opt,name=target_state,json=targetState,proto3,enum=gamenode.GameNodeStaticState" json:"target_state,omitempty"`
	ChangeTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=change_time,json=changeTime,proto3" json:"change_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChangeRequest) Reset() {
	*x = StateChangeRequest{}
	mi := &file_gamenode_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChangeRequest) ProtoMessage() {}

func (x *StateChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChangeRequest.ProtoReflect.Descriptor instead.
func (*StateChangeRequest) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{14}
}

func (x *StateChangeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StateChangeRequest) GetTargetState() GameNodeStaticState {
	if x != nil {
		return x.TargetState
	}
	return GameNodeStaticState_NODE_STATE_NORMAL
}

func (x *StateChangeRequest) GetChangeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangeTime
	}
	return nil
}

type StateChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ConfirmTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=confirm_time,json=confirmTime,proto3" json:"confirm_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChangeResponse) Reset() {
	*x = StateChangeResponse{}
	mi := &file_gamenode_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChangeResponse) ProtoMessage() {}

func (x *StateChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChangeResponse.ProtoReflect.Descriptor instead.
func (*StateChangeResponse) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{15}
}

func (x *StateChangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StateChangeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StateChangeResponse) GetConfirmTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmTime
	}
	return nil
}

// 硬件信息
type HardwareInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpus          []*CPUHardware         `protobuf:"bytes,1,rep,name=cpus,proto3" json:"cpus,omitempty"`
	Memories      []*MemoryHardware      `protobuf:"bytes,2,rep,name=memories,proto3" json:"memories,omitempty"`
	Gpus          []*GPUHardware         `protobuf:"bytes,3,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Storages      []*StorageDevice       `protobuf:"bytes,4,rep,name=storages,proto3" json:"storages,omitempty"`
	Networks      []*NetworkDevice       `protobuf:"bytes,5,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_gamenode_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{16}
}

func (x *HardwareInfo) GetCpus() []*CPUHardware {
	if x != nil {
		return x.Cpus
	}
	return nil
}

func (x *HardwareInfo) GetMemories() []*MemoryHardware {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *HardwareInfo) GetGpus() []*GPUHardware {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *HardwareInfo) GetStorages() []*StorageDevice {
	if x != nil {
		return x.Storages
	}
	return nil
}

func (x *HardwareInfo) GetNetworks() []*NetworkDevice {
	if x != nil {
		return x.Networks
	}
	return nil
}

type CPUHardware struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads       int32                  `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`
	Frequency     float64                `protobuf:"fixed64,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Cache         int64                  `protobuf:"varint,5,opt,name=cache,proto3" json:"cache,omitempty"`
	Architecture  string                 `protobuf:"bytes,6,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUHardware) Reset() {
	*x = CPUHardware{}
	mi := &file_gamenode_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUHardware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUHardware) ProtoMessage() {}

func (x *CPUHardware) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUHardware.ProtoReflect.Descriptor instead.
func (*CPUHardware) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{17}
}

func (x *CPUHardware) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CPUHardware) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPUHardware) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *CPUHardware) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *CPUHardware) GetCache() int64 {
	if x != nil {
		return x.Cache
	}
	return 0
}

func (x *CPUHardware) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type MemoryHardware struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Frequency     float64                `protobuf:"fixed64,3,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryHardware) Reset() {
	*x = MemoryHardware{}
	mi := &file_gamenode_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryHardware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryHardware) ProtoMessage() {}

func (x *MemoryHardware) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryHardware.ProtoReflect.Descriptor instead.
func (*MemoryHardware) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{18}
}

func (x *MemoryHardware) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MemoryHardware) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MemoryHardware) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type GPUHardware struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	MemoryTotal       int64                  `protobuf:"varint,2,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	Architecture      string                 `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	DriverVersion     string                 `protobuf:"bytes,4,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	ComputeCapability string                 `protobuf:"bytes,5,opt,name=compute_capability,json=computeCapability,proto3" json:"compute_capability,omitempty"`
	Tdp               int32                  `protobuf:"varint,6,opt,name=tdp,proto3" json:"tdp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GPUHardware) Reset() {
	*x = GPUHardware{}
	mi := &file_gamenode_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUHardware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUHardware) ProtoMessage() {}

func (x *GPUHardware) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUHardware.ProtoReflect.Descriptor instead.
func (*GPUHardware) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{19}
}

func (x *GPUHardware) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUHardware) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *GPUHardware) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *GPUHardware) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *GPUHardware) GetComputeCapability() string {
	if x != nil {
		return x.ComputeCapability
	}
	return ""
}

func (x *GPUHardware) GetTdp() int32 {
	if x != nil {
		return x.Tdp
	}
	return 0
}

type StorageDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Capacity      int64                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDevice) Reset() {
	*x = StorageDevice{}
	mi := &file_gamenode_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDevice) ProtoMessage() {}

func (x *StorageDevice) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDevice.ProtoReflect.Descriptor instead.
func (*StorageDevice) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{20}
}

func (x *StorageDevice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StorageDevice) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StorageDevice) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StorageDevice) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type NetworkDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Speed         int64                  `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkDevice) Reset() {
	*x = NetworkDevice{}
	mi := &file_gamenode_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDevice) ProtoMessage() {}

func (x *NetworkDevice) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkDevice.ProtoReflect.Descriptor instead.
func (*NetworkDevice) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{21}
}

func (x *NetworkDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkDevice) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkDevice) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NetworkDevice) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

// 系统信息
type SystemInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OsDistribution       string                 `protobuf:"bytes,1,opt,name=os_distribution,json=osDistribution,proto3" json:"os_distribution,omitempty"`
	OsVersion            string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsArchitecture       string                 `protobuf:"bytes,3,opt,name=os_architecture,json=osArchitecture,proto3" json:"os_architecture,omitempty"`
	KernelVersion        string                 `protobuf:"bytes,4,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	GpuDriverVersion     string                 `protobuf:"bytes,5,opt,name=gpu_driver_version,json=gpuDriverVersion,proto3" json:"gpu_driver_version,omitempty"`
	GpuComputeApiVersion string                 `protobuf:"bytes,6,opt,name=gpu_compute_api_version,json=gpuComputeApiVersion,proto3" json:"gpu_compute_api_version,omitempty"`
	DockerVersion        string                 `protobuf:"bytes,7,opt,name=docker_version,json=dockerVersion,proto3" json:"docker_version,omitempty"`
	ContainerdVersion    string                 `protobuf:"bytes,8,opt,name=containerd_version,json=containerdVersion,proto3" json:"containerd_version,omitempty"`
	RuncVersion          string                 `protobuf:"bytes,9,opt,name=runc_version,json=runcVersion,proto3" json:"runc_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_gamenode_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{22}
}

func (x *SystemInfo) GetOsDistribution() string {
	if x != nil {
		return x.OsDistribution
	}
	return ""
}

func (x *SystemInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SystemInfo) GetOsArchitecture() string {
	if x != nil {
		return x.OsArchitecture
	}
	return ""
}

func (x *SystemInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SystemInfo) GetGpuDriverVersion() string {
	if x != nil {
		return x.GpuDriverVersion
	}
	return ""
}

func (x *SystemInfo) GetGpuComputeApiVersion() string {
	if x != nil {
		return x.GpuComputeApiVersion
	}
	return ""
}

func (x *SystemInfo) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

func (x *SystemInfo) GetContainerdVersion() string {
	if x != nil {
		return x.ContainerdVersion
	}
	return ""
}

func (x *SystemInfo) GetRuncVersion() string {
	if x != nil {
		return x.RuncVersion
	}
	return ""
}

// 日志流
type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_gamenode_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{23}
}

func (x *LogRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LogRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *LogRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *LogRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *LogRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_gamenode_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{24}
}

func (x *LogEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LogEntry) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *LogEntry) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_gamenode_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{25}
}

func (x *LogResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Pipeline执行
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_gamenode_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{26}
}

func (x *ExecuteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecuteRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ExecuteRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecuteRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_gamenode_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamenode_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_gamenode_proto_rawDescGZIP(), []int{27}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_gamenode_proto protoreflect.FileDescriptor

const file_gamenode_proto_rawDesc = "" +
	"\n" +
	"\x0egamenode.proto\x12\bgamenode\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x03\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12C\n" +
	"\bhardware\x18\x06 \x03(\v2'.gamenode.RegisterRequest.HardwareEntryR\bhardware\x12=\n" +
	"\x06system\x18\a \x03(\v2%.gamenode.RegisterRequest.SystemEntryR\x06system\x12=\n" +
	"\x06labels\x18\b \x03(\v2%.gamenode.RegisterRequest.LabelsEntryR\x06labels\x1a;\n" +
	"\rHardwareEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vSystemEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1d.gamenode.GameNodeStaticStateR\x05state\"_\n" +
	"\x10HeartbeatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"E\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"o\n" +
	"\x0eMetricsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12/\n" +
	"\ametrics\x18\x03 \x01(\v2\x15.gamenode.MetricsInfoR\ametrics\"\xfc\x01\n" +
	"\vMetricsInfo\x12(\n" +
	"\x04cpus\x18\x01 \x03(\v2\x14.gamenode.CPUMetricsR\x04cpus\x12/\n" +
	"\x06memory\x18\x02 \x01(\v2\x17.gamenode.MemoryMetricsR\x06memory\x12(\n" +
	"\x04gpus\x18\x03 \x03(\v2\x14.gamenode.GPUMetricsR\x04gpus\x124\n" +
	"\bstorages\x18\x04 \x03(\v2\x18.gamenode.StorageMetricsR\bstorages\x122\n" +
	"\anetwork\x18\x05 \x01(\v2\x18.gamenode.NetworkMetricsR\anetwork\"h\n" +
	"\n" +
	"CPUMetrics\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x05R\athreads\x12\x14\n" +
	"\x05usage\x18\x04 \x01(\x01R\x05usage\"m\n" +
	"\rMemoryMetrics\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x03R\tavailable\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x03R\x04used\x12\x14\n" +
	"\x05usage\x18\x04 \x01(\x01R\x05usage\"\xc0\x01\n" +
	"\n" +
	"GPUMetrics\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12!\n" +
	"\fmemory_total\x18\x02 \x01(\x03R\vmemoryTotal\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\x01R\x05usage\x12\x1f\n" +
	"\vmemory_used\x18\x04 \x01(\x03R\n" +
	"memoryUsed\x12\x1f\n" +
	"\vmemory_free\x18\x05 \x01(\x03R\n" +
	"memoryFree\x12!\n" +
	"\fmemory_usage\x18\x06 \x01(\x01R\vmemoryUsage\"\xa8\x01\n" +
	"\x0eStorageMetrics\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x03R\bcapacity\x12\x12\n" +
	"\x04used\x18\x05 \x01(\x03R\x04used\x12\x12\n" +
	"\x04free\x18\x06 \x01(\x03R\x04free\x12\x14\n" +
	"\x05usage\x18\a \x01(\x01R\x05usage\"\x86\x01\n" +
	"\x0eNetworkMetrics\x12'\n" +
	"\x0finbound_traffic\x18\x01 \x01(\x01R\x0einboundTraffic\x12)\n" +
	"\x10outbound_traffic\x18\x02 \x01(\x01R\x0foutboundTraffic\x12 \n" +
	"\vconnections\x18\x03 \x01(\x05R\vconnections\"E\n" +
	"\x0fMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xaa\x01\n" +
	"\x0fResourceRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x122\n" +
	"\bhardware\x18\x03 \x01(\v2\x16.gamenode.HardwareInfoR\bhardware\x12,\n" +
	"\x06system\x18\x04 \x01(\v2\x14.gamenode.SystemInfoR\x06system\"F\n" +
	"\x10ResourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xac\x01\n" +
	"\x12StateChangeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12@\n" +
	"\ftarget_state\x18\x02 \x01(\x0e2\x1d.gamenode.GameNodeStaticStateR\vtargetState\x12;\n" +
	"\vchange_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"changeTime\"\x93\x01\n" +
	"\x13StateChangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12=\n" +
	"\fconfirm_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmTime\"\x84\x02\n" +
	"\fHardwareInfo\x12)\n" +
	"\x04cpus\x18\x01 \x03(\v2\x15.gamenode.CPUHardwareR\x04cpus\x124\n" +
	"\bmemories\x18\x02 \x03(\v2\x18.gamenode.MemoryHardwareR\bmemories\x12)\n" +
	"\x04gpus\x18\x03 \x03(\v2\x15.gamenode.GPUHardwareR\x04gpus\x123\n" +
	"\bstorages\x18\x04 \x03(\v2\x17.gamenode.StorageDeviceR\bstorages\x123\n" +
	"\bnetworks\x18\x05 \x03(\v2\x17.gamenode.NetworkDeviceR\bnetworks\"\xab\x01\n" +
	"\vCPUHardware\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x05R\athreads\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\x01R\tfrequency\x12\x14\n" +
	"\x05cache\x18\x05 \x01(\x03R\x05cache\x12\"\n" +
	"\farchitecture\x18\x06 \x01(\tR\farchitecture\"V\n" +
	"\x0eMemoryHardware\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\tfrequency\x18\x03 \x01(\x01R\tfrequency\"\xd2\x01\n" +
	"\vGPUHardware\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12!\n" +
	"\fmemory_total\x18\x02 \x01(\x03R\vmemoryTotal\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x12%\n" +
	"\x0edriver_version\x18\x04 \x01(\tR\rdriverVersion\x12-\n" +
	"\x12compute_capability\x18\x05 \x01(\tR\x11computeCapability\x12\x10\n" +
	"\x03tdp\x18\x06 \x01(\x05R\x03tdp\"i\n" +
	"\rStorageDevice\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x03R\bcapacity\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"y\n" +
	"\rNetworkDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x03R\x05speed\"\x82\x03\n" +
	"\n" +
	"SystemInfo\x12'\n" +
	"\x0fos_distribution\x18\x01 \x01(\tR\x0eosDistribution\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12'\n" +
	"\x0fos_architecture\x18\x03 \x01(\tR\x0eosArchitecture\x12%\n" +
	"\x0ekernel_version\x18\x04 \x01(\tR\rkernelVersion\x12,\n" +
	"\x12gpu_driver_version\x18\x05 \x01(\tR\x10gpuDriverVersion\x125\n" +
	"\x17gpu_compute_api_version\x18\x06 \x01(\tR\x14gpuComputeApiVersion\x12%\n" +
	"\x0edocker_version\x18\a \x01(\tR\rdockerVersion\x12-\n" +
	"\x12containerd_version\x18\b \x01(\tR\x11containerdVersion\x12!\n" +
	"\frunc_version\x18\t \x01(\tR\vruncVersion\"\x99\x01\n" +
	"\n" +
	"LogRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\"\xab\x01\n" +
	"\bLogEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"z\n" +
	"\vLogResponse\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.gamenode.LogEntryR\aentries\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xec\x01\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12H\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2(.gamenode.ExecuteRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage*a\n" +
	"\x13GameNodeStaticState\x12\x15\n" +
	"\x11NODE_STATE_NORMAL\x10\x00\x12\x1a\n" +
	"\x16NODE_STATE_MAINTENANCE\x10\x01\x12\x17\n" +
	"\x13NODE_STATE_DISABLED\x10\x022\xf1\x03\n" +
	"\x13GameNodeGRPCService\x12A\n" +
	"\bRegister\x12\x19.gamenode.RegisterRequest\x1a\x1a.gamenode.RegisterResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.gamenode.HeartbeatRequest\x1a\x1b.gamenode.HeartbeatResponse\x12D\n" +
	"\rReportMetrics\x12\x18.gamenode.MetricsRequest\x1a\x19.gamenode.MetricsResponse\x12G\n" +
	"\x0eReportResource\x12\x19.gamenode.ResourceRequest\x1a\x1a.gamenode.ResourceResponse\x12N\n" +
	"\x0fUpdateNodeState\x12\x1c.gamenode.StateChangeRequest\x1a\x1d.gamenode.StateChangeResponse\x122\n" +
	"\x03Log\x12\x14.gamenode.LogRequest\x1a\x15.gamenode.LogResponse\x12>\n" +
	"\aExecute\x12\x18.gamenode.ExecuteRequest\x1a\x19.gamenode.ExecuteResponseB8Z6github.com/open-beagle/beagle-wind-game/internal/protob\x06proto3"

var (
	file_gamenode_proto_rawDescOnce sync.Once
	file_gamenode_proto_rawDescData []byte
)

func file_gamenode_proto_rawDescGZIP() []byte {
	file_gamenode_proto_rawDescOnce.Do(func() {
		file_gamenode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamenode_proto_rawDesc), len(file_gamenode_proto_rawDesc)))
	})
	return file_gamenode_proto_rawDescData
}

var file_gamenode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gamenode_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_gamenode_proto_goTypes = []any{
	(GameNodeStaticState)(0),      // 0: gamenode.GameNodeStaticState
	(*RegisterRequest)(nil),       // 1: gamenode.RegisterRequest
	(*RegisterResponse)(nil),      // 2: gamenode.RegisterResponse
	(*HeartbeatRequest)(nil),      // 3: gamenode.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 4: gamenode.HeartbeatResponse
	(*MetricsRequest)(nil),        // 5: gamenode.MetricsRequest
	(*MetricsInfo)(nil),           // 6: gamenode.MetricsInfo
	(*CPUMetrics)(nil),            // 7: gamenode.CPUMetrics
	(*MemoryMetrics)(nil),         // 8: gamenode.MemoryMetrics
	(*GPUMetrics)(nil),            // 9: gamenode.GPUMetrics
	(*StorageMetrics)(nil),        // 10: gamenode.StorageMetrics
	(*NetworkMetrics)(nil),        // 11: gamenode.NetworkMetrics
	(*MetricsResponse)(nil),       // 12: gamenode.MetricsResponse
	(*ResourceRequest)(nil),       // 13: gamenode.ResourceRequest
	(*ResourceResponse)(nil),      // 14: gamenode.ResourceResponse
	(*StateChangeRequest)(nil),    // 15: gamenode.StateChangeRequest
	(*StateChangeResponse)(nil),   // 16: gamenode.StateChangeResponse
	(*HardwareInfo)(nil),          // 17: gamenode.HardwareInfo
	(*CPUHardware)(nil),           // 18: gamenode.CPUHardware
	(*MemoryHardware)(nil),        // 19: gamenode.MemoryHardware
	(*GPUHardware)(nil),           // 20: gamenode.GPUHardware
	(*StorageDevice)(nil),         // 21: gamenode.StorageDevice
	(*NetworkDevice)(nil),         // 22: gamenode.NetworkDevice
	(*SystemInfo)(nil),            // 23: gamenode.SystemInfo
	(*LogRequest)(nil),            // 24: gamenode.LogRequest
	(*LogEntry)(nil),              // 25: gamenode.LogEntry
	(*LogResponse)(nil),           // 26: gamenode.LogResponse
	(*ExecuteRequest)(nil),        // 27: gamenode.ExecuteRequest
	(*ExecuteResponse)(nil),       // 28: gamenode.ExecuteResponse
	nil,                           // 29: gamenode.RegisterRequest.HardwareEntry
	nil,                           // 30: gamenode.RegisterRequest.SystemEntry
	nil,                           // 31: gamenode.RegisterRequest.LabelsEntry
	nil,                           // 32: gamenode.ExecuteRequest.ParametersEntry
	(*timestamppb.Timestamp)(nil), // 33: google.protobuf.Timestamp
}
var file_gamenode_proto_depIdxs = []int32{
	29, // 0: gamenode.RegisterRequest.hardware:type_name -> gamenode.RegisterRequest.HardwareEntry
	30, // 1: gamenode.RegisterRequest.system:type_name -> gamenode.RegisterRequest.SystemEntry
	31, // 2: gamenode.RegisterRequest.labels:type_name -> gamenode.RegisterRequest.LabelsEntry
	0,  // 3: gamenode.RegisterResponse.state:type_name -> gamenode.GameNodeStaticState
	6,  // 4: gamenode.MetricsRequest.metrics:type_name -> gamenode.MetricsInfo
	7,  // 5: gamenode.MetricsInfo.cpus:type_name -> gamenode.CPUMetrics
	8,  // 6: gamenode.MetricsInfo.memory:type_name -> gamenode.MemoryMetrics
	9,  // 7: gamenode.MetricsInfo.gpus:type_name -> gamenode.GPUMetrics
	10, // 8: gamenode.MetricsInfo.storages:type_name -> gamenode.StorageMetrics
	11, // 9: gamenode.MetricsInfo.network:type_name -> gamenode.NetworkMetrics
	17, // 10: gamenode.ResourceRequest.hardware:type_name -> gamenode.HardwareInfo
	23, // 11: gamenode.ResourceRequest.system:type_name -> gamenode.SystemInfo
	0,  // 12: gamenode.StateChangeRequest.target_state:type_name -> gamenode.GameNodeStaticState
	33, // 13: gamenode.StateChangeRequest.change_time:type_name -> google.protobuf.Timestamp
	33, // 14: gamenode.StateChangeResponse.confirm_time:type_name -> google.protobuf.Timestamp
	18, // 15: gamenode.HardwareInfo.cpus:type_name -> gamenode.CPUHardware
	19, // 16: gamenode.HardwareInfo.memories:type_name -> gamenode.MemoryHardware
	20, // 17: gamenode.HardwareInfo.gpus:type_name -> gamenode.GPUHardware
	21, // 18: gamenode.HardwareInfo.storages:type_name -> gamenode.StorageDevice
	22, // 19: gamenode.HardwareInfo.networks:type_name -> gamenode.NetworkDevice
	25, // 20: gamenode.LogResponse.entries:type_name -> gamenode.LogEntry
	32, // 21: gamenode.ExecuteRequest.parameters:type_name -> gamenode.ExecuteRequest.ParametersEntry
	1,  // 22: gamenode.GameNodeGRPCService.Register:input_type -> gamenode.RegisterRequest
	3,  // 23: gamenode.GameNodeGRPCService.Heartbeat:input_type -> gamenode.HeartbeatRequest
	5,  // 24: gamenode.GameNodeGRPCService.ReportMetrics:input_type -> gamenode.MetricsRequest
	13, // 25: gamenode.GameNodeGRPCService.ReportResource:input_type -> gamenode.ResourceRequest
	15, // 26: gamenode.GameNodeGRPCService.UpdateNodeState:input_type -> gamenode.StateChangeRequest
	24, // 27: gamenode.GameNodeGRPCService.Log:input_type -> gamenode.LogRequest
	27, // 28: gamenode.GameNodeGRPCService.Execute:input_type -> gamenode.ExecuteRequest
	2,  // 29: gamenode.GameNodeGRPCService.Register:output_type -> gamenode.RegisterResponse
	4,  // 30: gamenode.GameNodeGRPCService.Heartbeat:output_type -> gamenode.HeartbeatResponse
	12, // 31: gamenode.GameNodeGRPCService.ReportMetrics:output_type -> gamenode.MetricsResponse
	14, // 32: gamenode.GameNodeGRPCService.ReportResource:output_type -> gamenode.ResourceResponse
	16, // 33: gamenode.GameNodeGRPCService.UpdateNodeState:output_type -> gamenode.StateChangeResponse
	26, // 34: gamenode.GameNodeGRPCService.Log:output_type -> gamenode.LogResponse
	28, // 35: gamenode.GameNodeGRPCService.Execute:output_type -> gamenode.ExecuteResponse
	29, // [29:36] is the sub-list for method output_type
	22, // [22:29] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_gamenode_proto_init() }
func file_gamenode_proto_init() {
	if File_gamenode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamenode_proto_rawDesc), len(file_gamenode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gamenode_proto_goTypes,
		DependencyIndexes: file_gamenode_proto_depIdxs,
		EnumInfos:         file_gamenode_proto_enumTypes,
		MessageInfos:      file_gamenode_proto_msgTypes,
	}.Build()
	File_gamenode_proto = out.File
	file_gamenode_proto_goTypes = nil
	file_gamenode_proto_depIdxs = nil
}
