// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: internal/proto/gamepipeline.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PipelineModel 表示流水线模板类型
type PipelineModel int32

const (
	PipelineModel_PIPELINE_MODEL_UNKNOWN        PipelineModel = 0
	PipelineModel_PIPELINE_MODEL_START_PLATFORM PipelineModel = 1
)

// Enum value maps for PipelineModel.
var (
	PipelineModel_name = map[int32]string{
		0: "PIPELINE_MODEL_UNKNOWN",
		1: "PIPELINE_MODEL_START_PLATFORM",
	}
	PipelineModel_value = map[string]int32{
		"PIPELINE_MODEL_UNKNOWN":        0,
		"PIPELINE_MODEL_START_PLATFORM": 1,
	}
)

func (x PipelineModel) Enum() *PipelineModel {
	p := new(PipelineModel)
	*p = x
	return p
}

func (x PipelineModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineModel) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_gamepipeline_proto_enumTypes[0].Descriptor()
}

func (PipelineModel) Type() protoreflect.EnumType {
	return &file_internal_proto_gamepipeline_proto_enumTypes[0]
}

func (x PipelineModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineModel.Descriptor instead.
func (PipelineModel) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{0}
}

// PipelineState 表示流水线状态
type PipelineState int32

const (
	PipelineState_PIPELINE_STATE_NOT_STARTED PipelineState = 0 // 未开始
	PipelineState_PIPELINE_STATE_PENDING     PipelineState = 1 // 等待中
	PipelineState_PIPELINE_STATE_RUNNING     PipelineState = 2 // 运行中
	PipelineState_PIPELINE_STATE_COMPLETED   PipelineState = 3 // 已完成
	PipelineState_PIPELINE_STATE_FAILED      PipelineState = 4 // 失败
	PipelineState_PIPELINE_STATE_CANCELED    PipelineState = 5 // 取消
)

// Enum value maps for PipelineState.
var (
	PipelineState_name = map[int32]string{
		0: "PIPELINE_STATE_NOT_STARTED",
		1: "PIPELINE_STATE_PENDING",
		2: "PIPELINE_STATE_RUNNING",
		3: "PIPELINE_STATE_COMPLETED",
		4: "PIPELINE_STATE_FAILED",
		5: "PIPELINE_STATE_CANCELED",
	}
	PipelineState_value = map[string]int32{
		"PIPELINE_STATE_NOT_STARTED": 0,
		"PIPELINE_STATE_PENDING":     1,
		"PIPELINE_STATE_RUNNING":     2,
		"PIPELINE_STATE_COMPLETED":   3,
		"PIPELINE_STATE_FAILED":      4,
		"PIPELINE_STATE_CANCELED":    5,
	}
)

func (x PipelineState) Enum() *PipelineState {
	p := new(PipelineState)
	*p = x
	return p
}

func (x PipelineState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_gamepipeline_proto_enumTypes[1].Descriptor()
}

func (PipelineState) Type() protoreflect.EnumType {
	return &file_internal_proto_gamepipeline_proto_enumTypes[1]
}

func (x PipelineState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineState.Descriptor instead.
func (PipelineState) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{1}
}

// StepState 表示步骤状态
type StepState int32

const (
	StepState_STEP_STATE_PENDING   StepState = 0 // 等待中
	StepState_STEP_STATE_RUNNING   StepState = 1 // 运行中
	StepState_STEP_STATE_COMPLETED StepState = 2 // 已完成
	StepState_STEP_STATE_FAILED    StepState = 3 // 失败
	StepState_STEP_STATE_SKIPPED   StepState = 4 // 已跳过
)

// Enum value maps for StepState.
var (
	StepState_name = map[int32]string{
		0: "STEP_STATE_PENDING",
		1: "STEP_STATE_RUNNING",
		2: "STEP_STATE_COMPLETED",
		3: "STEP_STATE_FAILED",
		4: "STEP_STATE_SKIPPED",
	}
	StepState_value = map[string]int32{
		"STEP_STATE_PENDING":   0,
		"STEP_STATE_RUNNING":   1,
		"STEP_STATE_COMPLETED": 2,
		"STEP_STATE_FAILED":    3,
		"STEP_STATE_SKIPPED":   4,
	}
)

func (x StepState) Enum() *StepState {
	p := new(StepState)
	*p = x
	return p
}

func (x StepState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_gamepipeline_proto_enumTypes[2].Descriptor()
}

func (StepState) Type() protoreflect.EnumType {
	return &file_internal_proto_gamepipeline_proto_enumTypes[2]
}

func (x StepState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepState.Descriptor instead.
func (StepState) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{2}
}

// StepStatus 步骤状态信息
type StepStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // 步骤 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // 步骤名称
	State         StepState              `protobuf:"varint,3,opt,name=state,proto3,enum=pipeline.StepState" json:"state,omitempty"`  // 步骤状态
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                           // 错误信息
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`                         // 输出信息
	Logs          []byte                 `protobuf:"bytes,6,opt,name=logs,proto3" json:"logs,omitempty"`                             // 日志数据
	Progress      float64                `protobuf:"fixed64,7,opt,name=progress,proto3" json:"progress,omitempty"`                   // 进度（0-100）
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`  // 开始时间
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`        // 结束时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStatus) Reset() {
	*x = StepStatus{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStatus) ProtoMessage() {}

func (x *StepStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStatus.ProtoReflect.Descriptor instead.
func (*StepStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{0}
}

func (x *StepStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StepStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepStatus) GetState() StepState {
	if x != nil {
		return x.State
	}
	return StepState_STEP_STATE_PENDING
}

func (x *StepStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StepStatus) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *StepStatus) GetLogs() []byte {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *StepStatus) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *StepStatus) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *StepStatus) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *StepStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ContainerConfig 容器配置
type ContainerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Privileged    bool                   `protobuf:"varint,3,opt,name=privileged,proto3" json:"privileged,omitempty"`
	Deploy        *DeployConfig          `protobuf:"bytes,4,opt,name=deploy,proto3" json:"deploy,omitempty"`
	SecurityOpt   []string               `protobuf:"bytes,5,rep,name=security_opt,json=securityOpt,proto3" json:"security_opt,omitempty"`
	CapAdd        []string               `protobuf:"bytes,6,rep,name=cap_add,json=capAdd,proto3" json:"cap_add,omitempty"`
	Tmpfs         []string               `protobuf:"bytes,7,rep,name=tmpfs,proto3" json:"tmpfs,omitempty"`
	Devices       []string               `protobuf:"bytes,8,rep,name=devices,proto3" json:"devices,omitempty"`
	Volumes       []string               `protobuf:"bytes,9,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Ports         []string               `protobuf:"bytes,10,rep,name=ports,proto3" json:"ports,omitempty"`
	Environment   map[string]string      `protobuf:"bytes,11,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Commands      []string               `protobuf:"bytes,12,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerConfig) Reset() {
	*x = ContainerConfig{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfig) ProtoMessage() {}

func (x *ContainerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfig.ProtoReflect.Descriptor instead.
func (*ContainerConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerConfig) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ContainerConfig) GetPrivileged() bool {
	if x != nil {
		return x.Privileged
	}
	return false
}

func (x *ContainerConfig) GetDeploy() *DeployConfig {
	if x != nil {
		return x.Deploy
	}
	return nil
}

func (x *ContainerConfig) GetSecurityOpt() []string {
	if x != nil {
		return x.SecurityOpt
	}
	return nil
}

func (x *ContainerConfig) GetCapAdd() []string {
	if x != nil {
		return x.CapAdd
	}
	return nil
}

func (x *ContainerConfig) GetTmpfs() []string {
	if x != nil {
		return x.Tmpfs
	}
	return nil
}

func (x *ContainerConfig) GetDevices() []string {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *ContainerConfig) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *ContainerConfig) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerConfig) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ContainerConfig) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

// DeployConfig 部署配置
type DeployConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     *ResourcesConfig       `protobuf:"bytes,1,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployConfig) Reset() {
	*x = DeployConfig{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployConfig) ProtoMessage() {}

func (x *DeployConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployConfig.ProtoReflect.Descriptor instead.
func (*DeployConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{2}
}

func (x *DeployConfig) GetResources() *ResourcesConfig {
	if x != nil {
		return x.Resources
	}
	return nil
}

// ResourcesConfig 资源配置
type ResourcesConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  *ReservationsConfig    `protobuf:"bytes,1,opt,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesConfig) Reset() {
	*x = ResourcesConfig{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesConfig) ProtoMessage() {}

func (x *ResourcesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesConfig.ProtoReflect.Descriptor instead.
func (*ResourcesConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{3}
}

func (x *ResourcesConfig) GetReservations() *ReservationsConfig {
	if x != nil {
		return x.Reservations
	}
	return nil
}

// ReservationsConfig 资源预留配置
type ReservationsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceConfig        `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationsConfig) Reset() {
	*x = ReservationsConfig{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationsConfig) ProtoMessage() {}

func (x *ReservationsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationsConfig.ProtoReflect.Descriptor instead.
func (*ReservationsConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{4}
}

func (x *ReservationsConfig) GetDevices() []*DeviceConfig {
	if x != nil {
		return x.Devices
	}
	return nil
}

// DeviceConfig 设备配置
type DeviceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfig) Reset() {
	*x = DeviceConfig{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfig) ProtoMessage() {}

func (x *DeviceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfig.ProtoReflect.Descriptor instead.
func (*DeviceConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceConfig) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// PipelineStep 流水线步骤
type PipelineStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Container     *ContainerConfig       `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineStep) Reset() {
	*x = PipelineStep{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStep) ProtoMessage() {}

func (x *PipelineStep) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStep.ProtoReflect.Descriptor instead.
func (*PipelineStep) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{6}
}

func (x *PipelineStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PipelineStep) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PipelineStep) GetContainer() *ContainerConfig {
	if x != nil {
		return x.Container
	}
	return nil
}

// PipelineStatus 表示 Pipeline 的状态
type PipelineStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                   // 节点 ID
	State         PipelineState          `protobuf:"varint,2,opt,name=state,proto3,enum=pipeline.PipelineState" json:"state,omitempty"`      // Pipeline 状态
	CurrentStep   int32                  `protobuf:"varint,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`   // 当前步骤索引
	TotalSteps    int32                  `protobuf:"varint,4,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`      // 总步骤数
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 错误信息
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`          // 开始时间
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                // 结束时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineStatus) Reset() {
	*x = PipelineStatus{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStatus) ProtoMessage() {}

func (x *PipelineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStatus.ProtoReflect.Descriptor instead.
func (*PipelineStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{7}
}

func (x *PipelineStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PipelineStatus) GetState() PipelineState {
	if x != nil {
		return x.State
	}
	return PipelineState_PIPELINE_STATE_NOT_STARTED
}

func (x *PipelineStatus) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *PipelineStatus) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *PipelineStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PipelineStatus) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *PipelineStatus) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *PipelineStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GamePipeline 表示一个游戏节点流水线模板
type GamePipeline struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model PipelineModel          `protobuf:"varint,2,opt,name=model,proto3,enum=pipeline.PipelineModel" json:"model,omitempty"`
	// 静态信息（模板定义）
	Name        string          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string          `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Envs        []string        `protobuf:"bytes,5,rep,name=envs,proto3" json:"envs,omitempty"`
	Args        []string        `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	Steps       []*PipelineStep `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	// 动态信息（执行状态）
	Status        *PipelineStatus `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GamePipeline) Reset() {
	*x = GamePipeline{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamePipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePipeline) ProtoMessage() {}

func (x *GamePipeline) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePipeline.ProtoReflect.Descriptor instead.
func (*GamePipeline) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{8}
}

func (x *GamePipeline) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GamePipeline) GetModel() PipelineModel {
	if x != nil {
		return x.Model
	}
	return PipelineModel_PIPELINE_MODEL_UNKNOWN
}

func (x *GamePipeline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GamePipeline) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GamePipeline) GetEnvs() []string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *GamePipeline) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *GamePipeline) GetSteps() []*PipelineStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *GamePipeline) GetStatus() *PipelineStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// CreatePipelineRequest 创建流水线请求
type CreatePipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      *GamePipeline          `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineRequest) Reset() {
	*x = CreatePipelineRequest{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineRequest) ProtoMessage() {}

func (x *CreatePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineRequest.ProtoReflect.Descriptor instead.
func (*CreatePipelineRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePipelineRequest) GetPipeline() *GamePipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

// CreatePipelineResponse 创建流水线响应
type CreatePipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineResponse) Reset() {
	*x = CreatePipelineResponse{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineResponse) ProtoMessage() {}

func (x *CreatePipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineResponse.ProtoReflect.Descriptor instead.
func (*CreatePipelineResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePipelineResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetPipelineRequest 获取流水线请求
type GetPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRequest) Reset() {
	*x = GetPipelineRequest{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRequest) ProtoMessage() {}

func (x *GetPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{11}
}

func (x *GetPipelineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetPipelineResponse 获取流水线响应
type GetPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      *GamePipeline          `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineResponse) Reset() {
	*x = GetPipelineResponse{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineResponse) ProtoMessage() {}

func (x *GetPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineResponse.ProtoReflect.Descriptor instead.
func (*GetPipelineResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{12}
}

func (x *GetPipelineResponse) GetPipeline() *GamePipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

// ListPipelinesRequest 获取流水线列表请求
type ListPipelinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Status        PipelineState          `protobuf:"varint,3,opt,name=status,proto3,enum=pipeline.PipelineState" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SortBy        string                 `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesRequest) Reset() {
	*x = ListPipelinesRequest{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesRequest) ProtoMessage() {}

func (x *ListPipelinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesRequest.ProtoReflect.Descriptor instead.
func (*ListPipelinesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{13}
}

func (x *ListPipelinesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPipelinesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListPipelinesRequest) GetStatus() PipelineState {
	if x != nil {
		return x.Status
	}
	return PipelineState_PIPELINE_STATE_NOT_STARTED
}

func (x *ListPipelinesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ListPipelinesRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListPipelinesRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListPipelinesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListPipelinesRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// ListPipelinesResponse 获取流水线列表响应
type ListPipelinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipelines     []*GamePipeline        `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesResponse) Reset() {
	*x = ListPipelinesResponse{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesResponse) ProtoMessage() {}

func (x *ListPipelinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesResponse.ProtoReflect.Descriptor instead.
func (*ListPipelinesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{14}
}

func (x *ListPipelinesResponse) GetPipelines() []*GamePipeline {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

func (x *ListPipelinesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UpdatePipelineRequest 更新流水线请求
type UpdatePipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      *GamePipeline          `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePipelineRequest) Reset() {
	*x = UpdatePipelineRequest{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePipelineRequest) ProtoMessage() {}

func (x *UpdatePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePipelineRequest.ProtoReflect.Descriptor instead.
func (*UpdatePipelineRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePipelineRequest) GetPipeline() *GamePipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

// UpdatePipelineResponse 更新流水线响应
type UpdatePipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePipelineResponse) Reset() {
	*x = UpdatePipelineResponse{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePipelineResponse) ProtoMessage() {}

func (x *UpdatePipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePipelineResponse.ProtoReflect.Descriptor instead.
func (*UpdatePipelineResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{16}
}

func (x *UpdatePipelineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// DeletePipelineRequest 删除流水线请求
type DeletePipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePipelineRequest) Reset() {
	*x = DeletePipelineRequest{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePipelineRequest) ProtoMessage() {}

func (x *DeletePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePipelineRequest.ProtoReflect.Descriptor instead.
func (*DeletePipelineRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{17}
}

func (x *DeletePipelineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeletePipelineRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// DeletePipelineResponse 删除流水线响应
type DeletePipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePipelineResponse) Reset() {
	*x = DeletePipelineResponse{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePipelineResponse) ProtoMessage() {}

func (x *DeletePipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePipelineResponse.ProtoReflect.Descriptor instead.
func (*DeletePipelineResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{18}
}

func (x *DeletePipelineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ExecutePipelineRequest 执行流水线请求
type ExecutePipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePipelineRequest) Reset() {
	*x = ExecutePipelineRequest{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePipelineRequest) ProtoMessage() {}

func (x *ExecutePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePipelineRequest.ProtoReflect.Descriptor instead.
func (*ExecutePipelineRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{19}
}

func (x *ExecutePipelineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ExecutePipelineResponse 执行流水线响应
type ExecutePipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePipelineResponse) Reset() {
	*x = ExecutePipelineResponse{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePipelineResponse) ProtoMessage() {}

func (x *ExecutePipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePipelineResponse.ProtoReflect.Descriptor instead.
func (*ExecutePipelineResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{20}
}

func (x *ExecutePipelineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PipelineStreamRequest 流水线流式请求
type PipelineStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 心跳消息
	Heartbeat     *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineStreamRequest) Reset() {
	*x = PipelineStreamRequest{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStreamRequest) ProtoMessage() {}

func (x *PipelineStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStreamRequest.ProtoReflect.Descriptor instead.
func (*PipelineStreamRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{21}
}

func (x *PipelineStreamRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

// PipelineStreamResponse 流水线流式响应
type PipelineStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*PipelineStreamResponse_HeartbeatAck
	//	*PipelineStreamResponse_Pipeline
	//	*PipelineStreamResponse_Cancel
	Response      isPipelineStreamResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineStreamResponse) Reset() {
	*x = PipelineStreamResponse{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStreamResponse) ProtoMessage() {}

func (x *PipelineStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStreamResponse.ProtoReflect.Descriptor instead.
func (*PipelineStreamResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{22}
}

func (x *PipelineStreamResponse) GetResponse() isPipelineStreamResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PipelineStreamResponse) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Response.(*PipelineStreamResponse_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *PipelineStreamResponse) GetPipeline() *GamePipeline {
	if x != nil {
		if x, ok := x.Response.(*PipelineStreamResponse_Pipeline); ok {
			return x.Pipeline
		}
	}
	return nil
}

func (x *PipelineStreamResponse) GetCancel() *CancelCommand {
	if x != nil {
		if x, ok := x.Response.(*PipelineStreamResponse_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isPipelineStreamResponse_Response interface {
	isPipelineStreamResponse_Response()
}

type PipelineStreamResponse_HeartbeatAck struct {
	// 心跳确认
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,1,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type PipelineStreamResponse_Pipeline struct {
	// 流水线任务
	Pipeline *GamePipeline `protobuf:"bytes,2,opt,name=pipeline,proto3,oneof"`
}

type PipelineStreamResponse_Cancel struct {
	// 取消命令
	Cancel *CancelCommand `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

func (*PipelineStreamResponse_HeartbeatAck) isPipelineStreamResponse_Response() {}

func (*PipelineStreamResponse_Pipeline) isPipelineStreamResponse_Response() {}

func (*PipelineStreamResponse_Cancel) isPipelineStreamResponse_Response() {}

// Heartbeat 心跳消息
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PipelineIds   []string               `protobuf:"bytes,3,rep,name=pipeline_ids,json=pipelineIds,proto3" json:"pipeline_ids,omitempty"` // 正在运行的 Pipeline IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{23}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Heartbeat) GetPipelineIds() []string {
	if x != nil {
		return x.PipelineIds
	}
	return nil
}

// HeartbeatAck 心跳确认
type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{24}
}

func (x *HeartbeatAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// CancelCommand 取消命令
type CancelCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCommand) Reset() {
	*x = CancelCommand{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCommand) ProtoMessage() {}

func (x *CancelCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCommand.ProtoReflect.Descriptor instead.
func (*CancelCommand) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{25}
}

func (x *CancelCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// UpdatePipelineStatusRequest 更新流水线状态请求
type UpdatePipelineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Status        *PipelineStatus        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePipelineStatusRequest) Reset() {
	*x = UpdatePipelineStatusRequest{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePipelineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePipelineStatusRequest) ProtoMessage() {}

func (x *UpdatePipelineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePipelineStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePipelineStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{26}
}

func (x *UpdatePipelineStatusRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *UpdatePipelineStatusRequest) GetStatus() *PipelineStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// UpdatePipelineStatusResponse 更新流水线状态响应
type UpdatePipelineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePipelineStatusResponse) Reset() {
	*x = UpdatePipelineStatusResponse{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePipelineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePipelineStatusResponse) ProtoMessage() {}

func (x *UpdatePipelineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePipelineStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdatePipelineStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{27}
}

func (x *UpdatePipelineStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// UpdateStepStatusRequest 更新步骤状态请求
type UpdateStepStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Status        *StepStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStepStatusRequest) Reset() {
	*x = UpdateStepStatusRequest{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStepStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStepStatusRequest) ProtoMessage() {}

func (x *UpdateStepStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStepStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStepStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateStepStatusRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *UpdateStepStatusRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *UpdateStepStatusRequest) GetStatus() *StepStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// UpdateStepStatusResponse 更新步骤状态响应
type UpdateStepStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStepStatusResponse) Reset() {
	*x = UpdateStepStatusResponse{}
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStepStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStepStatusResponse) ProtoMessage() {}

func (x *UpdateStepStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamepipeline_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStepStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStepStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamepipeline_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateStepStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_proto_gamepipeline_proto protoreflect.FileDescriptor

const file_internal_proto_gamepipeline_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/gamepipeline.proto\x12\bpipeline\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x02\n" +
	"\n" +
	"StepStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x05state\x18\x03 \x01(\x0e2\x13.pipeline.StepStateR\x05state\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x12\n" +
	"\x04logs\x18\x06 \x01(\fR\x04logs\x12\x1a\n" +
	"\bprogress\x18\a \x01(\x01R\bprogress\x129\n" +
	"\n" +
	"start_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd9\x03\n" +
	"\x0fContainerConfig\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1e\n" +
	"\n" +
	"privileged\x18\x03 \x01(\bR\n" +
	"privileged\x12.\n" +
	"\x06deploy\x18\x04 \x01(\v2\x16.pipeline.DeployConfigR\x06deploy\x12!\n" +
	"\fsecurity_opt\x18\x05 \x03(\tR\vsecurityOpt\x12\x17\n" +
	"\acap_add\x18\x06 \x03(\tR\x06capAdd\x12\x14\n" +
	"\x05tmpfs\x18\a \x03(\tR\x05tmpfs\x12\x18\n" +
	"\adevices\x18\b \x03(\tR\adevices\x12\x18\n" +
	"\avolumes\x18\t \x03(\tR\avolumes\x12\x14\n" +
	"\x05ports\x18\n" +
	" \x03(\tR\x05ports\x12L\n" +
	"\venvironment\x18\v \x03(\v2*.pipeline.ContainerConfig.EnvironmentEntryR\venvironment\x12\x1a\n" +
	"\bcommands\x18\f \x03(\tR\bcommands\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\fDeployConfig\x127\n" +
	"\tresources\x18\x01 \x01(\v2\x19.pipeline.ResourcesConfigR\tresources\"S\n" +
	"\x0fResourcesConfig\x12@\n" +
	"\freservations\x18\x01 \x01(\v2\x1c.pipeline.ReservationsConfigR\freservations\"F\n" +
	"\x12ReservationsConfig\x120\n" +
	"\adevices\x18\x01 \x03(\v2\x16.pipeline.DeviceConfigR\adevices\"2\n" +
	"\fDeviceConfig\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\"o\n" +
	"\fPipelineStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x127\n" +
	"\tcontainer\x18\x03 \x01(\v2\x19.pipeline.ContainerConfigR\tcontainer\"\xee\x02\n" +
	"\x0ePipelineStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.pipeline.PipelineStateR\x05state\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\x05R\vcurrentStep\x12\x1f\n" +
	"\vtotal_steps\x18\x04 \x01(\x05R\n" +
	"totalSteps\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8b\x02\n" +
	"\fGamePipeline\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x05model\x18\x02 \x01(\x0e2\x17.pipeline.PipelineModelR\x05model\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04envs\x18\x05 \x03(\tR\x04envs\x12\x12\n" +
	"\x04args\x18\x06 \x03(\tR\x04args\x12,\n" +
	"\x05steps\x18\a \x03(\v2\x16.pipeline.PipelineStepR\x05steps\x120\n" +
	"\x06status\x18\b \x01(\v2\x18.pipeline.PipelineStatusR\x06status\"K\n" +
	"\x15CreatePipelineRequest\x122\n" +
	"\bpipeline\x18\x01 \x01(\v2\x16.pipeline.GamePipelineR\bpipeline\"(\n" +
	"\x16CreatePipelineResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12GetPipelineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x13GetPipelineResponse\x122\n" +
	"\bpipeline\x18\x01 \x01(\v2\x16.pipeline.GamePipelineR\bpipeline\"\xb2\x02\n" +
	"\x14ListPipelinesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.pipeline.PipelineStateR\x06status\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\tR\tsortOrder\"c\n" +
	"\x15ListPipelinesResponse\x124\n" +
	"\tpipelines\x18\x01 \x03(\v2\x16.pipeline.GamePipelineR\tpipelines\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"K\n" +
	"\x15UpdatePipelineRequest\x122\n" +
	"\bpipeline\x18\x01 \x01(\v2\x16.pipeline.GamePipelineR\bpipeline\"2\n" +
	"\x16UpdatePipelineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"=\n" +
	"\x15DeletePipelineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"2\n" +
	"\x16DeletePipelineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x16ExecutePipelineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17ExecutePipelineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x15PipelineStreamRequest\x121\n" +
	"\theartbeat\x18\x01 \x01(\v2\x13.pipeline.HeartbeatR\theartbeat\"\xcc\x01\n" +
	"\x16PipelineStreamResponse\x12=\n" +
	"\rheartbeat_ack\x18\x01 \x01(\v2\x16.pipeline.HeartbeatAckH\x00R\fheartbeatAck\x124\n" +
	"\bpipeline\x18\x02 \x01(\v2\x16.pipeline.GamePipelineH\x00R\bpipeline\x121\n" +
	"\x06cancel\x18\x03 \x01(\v2\x17.pipeline.CancelCommandH\x00R\x06cancelB\n" +
	"\n" +
	"\bresponse\"\x81\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fpipeline_ids\x18\x03 \x03(\tR\vpipelineIds\"(\n" +
	"\fHeartbeatAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\rCancelCommand\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"p\n" +
	"\x1bUpdatePipelineStatusRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x120\n" +
	"\x06status\x18\x02 \x01(\v2\x18.pipeline.PipelineStatusR\x06status\"8\n" +
	"\x1cUpdatePipelineStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x81\x01\n" +
	"\x17UpdateStepStatusRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12,\n" +
	"\x06status\x18\x03 \x01(\v2\x14.pipeline.StepStatusR\x06status\"4\n" +
	"\x18UpdateStepStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*N\n" +
	"\rPipelineModel\x12\x1a\n" +
	"\x16PIPELINE_MODEL_UNKNOWN\x10\x00\x12!\n" +
	"\x1dPIPELINE_MODEL_START_PLATFORM\x10\x01*\xbd\x01\n" +
	"\rPipelineState\x12\x1e\n" +
	"\x1aPIPELINE_STATE_NOT_STARTED\x10\x00\x12\x1a\n" +
	"\x16PIPELINE_STATE_PENDING\x10\x01\x12\x1a\n" +
	"\x16PIPELINE_STATE_RUNNING\x10\x02\x12\x1c\n" +
	"\x18PIPELINE_STATE_COMPLETED\x10\x03\x12\x19\n" +
	"\x15PIPELINE_STATE_FAILED\x10\x04\x12\x1b\n" +
	"\x17PIPELINE_STATE_CANCELED\x10\x05*\x84\x01\n" +
	"\tStepState\x12\x16\n" +
	"\x12STEP_STATE_PENDING\x10\x00\x12\x16\n" +
	"\x12STEP_STATE_RUNNING\x10\x01\x12\x18\n" +
	"\x14STEP_STATE_COMPLETED\x10\x02\x12\x15\n" +
	"\x11STEP_STATE_FAILED\x10\x03\x12\x16\n" +
	"\x12STEP_STATE_SKIPPED\x10\x042\xb4\x02\n" +
	"\x17GamePipelineGRPCService\x12W\n" +
	"\x0ePipelineStream\x12\x1f.pipeline.PipelineStreamRequest\x1a .pipeline.PipelineStreamResponse(\x010\x01\x12e\n" +
	"\x14UpdatePipelineStatus\x12%.pipeline.UpdatePipelineStatusRequest\x1a&.pipeline.UpdatePipelineStatusResponse\x12Y\n" +
	"\x10UpdateStepStatus\x12!.pipeline.UpdateStepStatusRequest\x1a\".pipeline.UpdateStepStatusResponseB8Z6github.com/open-beagle/beagle-wind-game/internal/protob\x06proto3"

var (
	file_internal_proto_gamepipeline_proto_rawDescOnce sync.Once
	file_internal_proto_gamepipeline_proto_rawDescData []byte
)

func file_internal_proto_gamepipeline_proto_rawDescGZIP() []byte {
	file_internal_proto_gamepipeline_proto_rawDescOnce.Do(func() {
		file_internal_proto_gamepipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_gamepipeline_proto_rawDesc), len(file_internal_proto_gamepipeline_proto_rawDesc)))
	})
	return file_internal_proto_gamepipeline_proto_rawDescData
}

var file_internal_proto_gamepipeline_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_proto_gamepipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_internal_proto_gamepipeline_proto_goTypes = []any{
	(PipelineModel)(0),                   // 0: pipeline.PipelineModel
	(PipelineState)(0),                   // 1: pipeline.PipelineState
	(StepState)(0),                       // 2: pipeline.StepState
	(*StepStatus)(nil),                   // 3: pipeline.StepStatus
	(*ContainerConfig)(nil),              // 4: pipeline.ContainerConfig
	(*DeployConfig)(nil),                 // 5: pipeline.DeployConfig
	(*ResourcesConfig)(nil),              // 6: pipeline.ResourcesConfig
	(*ReservationsConfig)(nil),           // 7: pipeline.ReservationsConfig
	(*DeviceConfig)(nil),                 // 8: pipeline.DeviceConfig
	(*PipelineStep)(nil),                 // 9: pipeline.PipelineStep
	(*PipelineStatus)(nil),               // 10: pipeline.PipelineStatus
	(*GamePipeline)(nil),                 // 11: pipeline.GamePipeline
	(*CreatePipelineRequest)(nil),        // 12: pipeline.CreatePipelineRequest
	(*CreatePipelineResponse)(nil),       // 13: pipeline.CreatePipelineResponse
	(*GetPipelineRequest)(nil),           // 14: pipeline.GetPipelineRequest
	(*GetPipelineResponse)(nil),          // 15: pipeline.GetPipelineResponse
	(*ListPipelinesRequest)(nil),         // 16: pipeline.ListPipelinesRequest
	(*ListPipelinesResponse)(nil),        // 17: pipeline.ListPipelinesResponse
	(*UpdatePipelineRequest)(nil),        // 18: pipeline.UpdatePipelineRequest
	(*UpdatePipelineResponse)(nil),       // 19: pipeline.UpdatePipelineResponse
	(*DeletePipelineRequest)(nil),        // 20: pipeline.DeletePipelineRequest
	(*DeletePipelineResponse)(nil),       // 21: pipeline.DeletePipelineResponse
	(*ExecutePipelineRequest)(nil),       // 22: pipeline.ExecutePipelineRequest
	(*ExecutePipelineResponse)(nil),      // 23: pipeline.ExecutePipelineResponse
	(*PipelineStreamRequest)(nil),        // 24: pipeline.PipelineStreamRequest
	(*PipelineStreamResponse)(nil),       // 25: pipeline.PipelineStreamResponse
	(*Heartbeat)(nil),                    // 26: pipeline.Heartbeat
	(*HeartbeatAck)(nil),                 // 27: pipeline.HeartbeatAck
	(*CancelCommand)(nil),                // 28: pipeline.CancelCommand
	(*UpdatePipelineStatusRequest)(nil),  // 29: pipeline.UpdatePipelineStatusRequest
	(*UpdatePipelineStatusResponse)(nil), // 30: pipeline.UpdatePipelineStatusResponse
	(*UpdateStepStatusRequest)(nil),      // 31: pipeline.UpdateStepStatusRequest
	(*UpdateStepStatusResponse)(nil),     // 32: pipeline.UpdateStepStatusResponse
	nil,                                  // 33: pipeline.ContainerConfig.EnvironmentEntry
	(*timestamppb.Timestamp)(nil),        // 34: google.protobuf.Timestamp
}
var file_internal_proto_gamepipeline_proto_depIdxs = []int32{
	2,  // 0: pipeline.StepStatus.state:type_name -> pipeline.StepState
	34, // 1: pipeline.StepStatus.start_time:type_name -> google.protobuf.Timestamp
	34, // 2: pipeline.StepStatus.end_time:type_name -> google.protobuf.Timestamp
	34, // 3: pipeline.StepStatus.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 4: pipeline.ContainerConfig.deploy:type_name -> pipeline.DeployConfig
	33, // 5: pipeline.ContainerConfig.environment:type_name -> pipeline.ContainerConfig.EnvironmentEntry
	6,  // 6: pipeline.DeployConfig.resources:type_name -> pipeline.ResourcesConfig
	7,  // 7: pipeline.ResourcesConfig.reservations:type_name -> pipeline.ReservationsConfig
	8,  // 8: pipeline.ReservationsConfig.devices:type_name -> pipeline.DeviceConfig
	4,  // 9: pipeline.PipelineStep.container:type_name -> pipeline.ContainerConfig
	1,  // 10: pipeline.PipelineStatus.state:type_name -> pipeline.PipelineState
	34, // 11: pipeline.PipelineStatus.start_time:type_name -> google.protobuf.Timestamp
	34, // 12: pipeline.PipelineStatus.end_time:type_name -> google.protobuf.Timestamp
	34, // 13: pipeline.PipelineStatus.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 14: pipeline.GamePipeline.model:type_name -> pipeline.PipelineModel
	9,  // 15: pipeline.GamePipeline.steps:type_name -> pipeline.PipelineStep
	10, // 16: pipeline.GamePipeline.status:type_name -> pipeline.PipelineStatus
	11, // 17: pipeline.CreatePipelineRequest.pipeline:type_name -> pipeline.GamePipeline
	11, // 18: pipeline.GetPipelineResponse.pipeline:type_name -> pipeline.GamePipeline
	1,  // 19: pipeline.ListPipelinesRequest.status:type_name -> pipeline.PipelineState
	34, // 20: pipeline.ListPipelinesRequest.start_time:type_name -> google.protobuf.Timestamp
	34, // 21: pipeline.ListPipelinesRequest.end_time:type_name -> google.protobuf.Timestamp
	11, // 22: pipeline.ListPipelinesResponse.pipelines:type_name -> pipeline.GamePipeline
	11, // 23: pipeline.UpdatePipelineRequest.pipeline:type_name -> pipeline.GamePipeline
	26, // 24: pipeline.PipelineStreamRequest.heartbeat:type_name -> pipeline.Heartbeat
	27, // 25: pipeline.PipelineStreamResponse.heartbeat_ack:type_name -> pipeline.HeartbeatAck
	11, // 26: pipeline.PipelineStreamResponse.pipeline:type_name -> pipeline.GamePipeline
	28, // 27: pipeline.PipelineStreamResponse.cancel:type_name -> pipeline.CancelCommand
	34, // 28: pipeline.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	10, // 29: pipeline.UpdatePipelineStatusRequest.status:type_name -> pipeline.PipelineStatus
	3,  // 30: pipeline.UpdateStepStatusRequest.status:type_name -> pipeline.StepStatus
	24, // 31: pipeline.GamePipelineGRPCService.PipelineStream:input_type -> pipeline.PipelineStreamRequest
	29, // 32: pipeline.GamePipelineGRPCService.UpdatePipelineStatus:input_type -> pipeline.UpdatePipelineStatusRequest
	31, // 33: pipeline.GamePipelineGRPCService.UpdateStepStatus:input_type -> pipeline.UpdateStepStatusRequest
	25, // 34: pipeline.GamePipelineGRPCService.PipelineStream:output_type -> pipeline.PipelineStreamResponse
	30, // 35: pipeline.GamePipelineGRPCService.UpdatePipelineStatus:output_type -> pipeline.UpdatePipelineStatusResponse
	32, // 36: pipeline.GamePipelineGRPCService.UpdateStepStatus:output_type -> pipeline.UpdateStepStatusResponse
	34, // [34:37] is the sub-list for method output_type
	31, // [31:34] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_internal_proto_gamepipeline_proto_init() }
func file_internal_proto_gamepipeline_proto_init() {
	if File_internal_proto_gamepipeline_proto != nil {
		return
	}
	file_internal_proto_gamepipeline_proto_msgTypes[22].OneofWrappers = []any{
		(*PipelineStreamResponse_HeartbeatAck)(nil),
		(*PipelineStreamResponse_Pipeline)(nil),
		(*PipelineStreamResponse_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_gamepipeline_proto_rawDesc), len(file_internal_proto_gamepipeline_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gamepipeline_proto_goTypes,
		DependencyIndexes: file_internal_proto_gamepipeline_proto_depIdxs,
		EnumInfos:         file_internal_proto_gamepipeline_proto_enumTypes,
		MessageInfos:      file_internal_proto_gamepipeline_proto_msgTypes,
	}.Build()
	File_internal_proto_gamepipeline_proto = out.File
	file_internal_proto_gamepipeline_proto_goTypes = nil
	file_internal_proto_gamepipeline_proto_depIdxs = nil
}
