// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: internal/proto/gamenode.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Step 状态枚举
type StepStatus int32

const (
	StepStatus_PENDING   StepStatus = 0
	StepStatus_RUNNING   StepStatus = 1
	StepStatus_COMPLETED StepStatus = 2
	StepStatus_FAILED    StepStatus = 3
	StepStatus_CANCELLED StepStatus = 4
)

// Enum value maps for StepStatus.
var (
	StepStatus_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "COMPLETED",
		3: "FAILED",
		4: "CANCELLED",
	}
	StepStatus_value = map[string]int32{
		"PENDING":   0,
		"RUNNING":   1,
		"COMPLETED": 2,
		"FAILED":    3,
		"CANCELLED": 4,
	}
)

func (x StepStatus) Enum() *StepStatus {
	p := new(StepStatus)
	*p = x
	return p
}

func (x StepStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_gamenode_proto_enumTypes[0].Descriptor()
}

func (StepStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_gamenode_proto_enumTypes[0]
}

func (x StepStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepStatus.Descriptor instead.
func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{0}
}

// 节点类型枚举
type NodeType int32

const (
	NodeType_NODE_TYPE_UNKNOWN   NodeType = 0 // 未知类型
	NodeType_NODE_TYPE_PHYSICAL  NodeType = 1 // 物理节点
	NodeType_NODE_TYPE_VIRTUAL   NodeType = 2 // 虚拟节点
	NodeType_NODE_TYPE_CONTAINER NodeType = 3 // 容器节点
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNKNOWN",
		1: "NODE_TYPE_PHYSICAL",
		2: "NODE_TYPE_VIRTUAL",
		3: "NODE_TYPE_CONTAINER",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNKNOWN":   0,
		"NODE_TYPE_PHYSICAL":  1,
		"NODE_TYPE_VIRTUAL":   2,
		"NODE_TYPE_CONTAINER": 3,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_gamenode_proto_enumTypes[1].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_internal_proto_gamenode_proto_enumTypes[1]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{1}
}

// 节点状态枚举
type GameNodeState int32

const (
	GameNodeState_NODE_STATE_OFFLINE     GameNodeState = 0 // 离线
	GameNodeState_NODE_STATE_ONLINE      GameNodeState = 1 // 在线
	GameNodeState_NODE_STATE_MAINTENANCE GameNodeState = 2 // 维护
	GameNodeState_NODE_STATE_READY       GameNodeState = 3 // 就绪
	GameNodeState_NODE_STATE_BUSY        GameNodeState = 4 // 忙碌
	GameNodeState_NODE_STATE_ERROR       GameNodeState = 5 // 错误
)

// Enum value maps for GameNodeState.
var (
	GameNodeState_name = map[int32]string{
		0: "NODE_STATE_OFFLINE",
		1: "NODE_STATE_ONLINE",
		2: "NODE_STATE_MAINTENANCE",
		3: "NODE_STATE_READY",
		4: "NODE_STATE_BUSY",
		5: "NODE_STATE_ERROR",
	}
	GameNodeState_value = map[string]int32{
		"NODE_STATE_OFFLINE":     0,
		"NODE_STATE_ONLINE":      1,
		"NODE_STATE_MAINTENANCE": 2,
		"NODE_STATE_READY":       3,
		"NODE_STATE_BUSY":        4,
		"NODE_STATE_ERROR":       5,
	}
)

func (x GameNodeState) Enum() *GameNodeState {
	p := new(GameNodeState)
	*p = x
	return p
}

func (x GameNodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameNodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_gamenode_proto_enumTypes[2].Descriptor()
}

func (GameNodeState) Type() protoreflect.EnumType {
	return &file_internal_proto_gamenode_proto_enumTypes[2]
}

func (x GameNodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameNodeState.Descriptor instead.
func (GameNodeState) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{2}
}

// 节点注册
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // 此处仍使用string，而不是枚举，避免兼容性问题
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Hardware      map[string]string      `protobuf:"bytes,6,rep,name=hardware,proto3" json:"hardware,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	System        map[string]string      `protobuf:"bytes,7,rep,name=system,proto3" json:"system,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HardwareInfo  *HardwareInfo          `protobuf:"bytes,9,opt,name=hardware_info,json=hardwareInfo,proto3" json:"hardware_info,omitempty"` // 新增详细硬件信息
	SystemInfo    *SystemInfo            `protobuf:"bytes,10,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`      // 新增详细系统信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *RegisterRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RegisterRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisterRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RegisterRequest) GetHardware() map[string]string {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *RegisterRequest) GetSystem() map[string]string {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetHardwareInfo() *HardwareInfo {
	if x != nil {
		return x.HardwareInfo
	}
	return nil
}

func (x *RegisterRequest) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 心跳
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        *GameNodeStatus        `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // 修改resource_info为status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() *GameNodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 节点指标报告
type MetricsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsReport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricsReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsReport) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{5}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// 资源信息更新
type ResourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeState     GameNodeState          `protobuf:"varint,3,opt,name=node_state,json=nodeState,proto3,enum=gamenode.GameNodeState" json:"node_state,omitempty"` // 修改node_status为node_state并使用枚举类型
	NodeType      NodeType               `protobuf:"varint,4,opt,name=node_type,json=nodeType,proto3,enum=gamenode.NodeType" json:"node_type,omitempty"`         // 修改字段编号
	Hardware      *HardwareInfo          `protobuf:"bytes,5,opt,name=hardware,proto3" json:"hardware,omitempty"`                                                 // 修改字段编号
	System        *SystemInfo            `protobuf:"bytes,6,opt,name=system,proto3" json:"system,omitempty"`                                                     // 修改字段编号
	Metrics       *MetricsInfo           `protobuf:"bytes,7,opt,name=metrics,proto3" json:"metrics,omitempty"`                                                   // 修改字段编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ResourceInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ResourceInfo) GetNodeState() GameNodeState {
	if x != nil {
		return x.NodeState
	}
	return GameNodeState_NODE_STATE_OFFLINE
}

func (x *ResourceInfo) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNKNOWN
}

func (x *ResourceInfo) GetHardware() *HardwareInfo {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *ResourceInfo) GetSystem() *SystemInfo {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *ResourceInfo) GetMetrics() *MetricsInfo {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// 硬件信息 - 重构为扁平结构
type HardwareInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpus          []*CPUHardware         `protobuf:"bytes,1,rep,name=cpus,proto3" json:"cpus,omitempty"`
	Memories      []*MemoryHardware      `protobuf:"bytes,2,rep,name=memories,proto3" json:"memories,omitempty"`
	Gpus          []*GPUHardware         `protobuf:"bytes,3,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Storages      []*StorageDevice       `protobuf:"bytes,4,rep,name=storages,proto3" json:"storages,omitempty"`
	Networks      []*NetworkDevice       `protobuf:"bytes,5,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{7}
}

func (x *HardwareInfo) GetCpus() []*CPUHardware {
	if x != nil {
		return x.Cpus
	}
	return nil
}

func (x *HardwareInfo) GetMemories() []*MemoryHardware {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *HardwareInfo) GetGpus() []*GPUHardware {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *HardwareInfo) GetStorages() []*StorageDevice {
	if x != nil {
		return x.Storages
	}
	return nil
}

func (x *HardwareInfo) GetNetworks() []*NetworkDevice {
	if x != nil {
		return x.Networks
	}
	return nil
}

type CPUHardware struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads       int32                  `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`
	Frequency     float64                `protobuf:"fixed64,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Cache         int64                  `protobuf:"varint,5,opt,name=cache,proto3" json:"cache,omitempty"`
	Architecture  string                 `protobuf:"bytes,6,opt,name=architecture,proto3" json:"architecture,omitempty"` // 新增架构字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUHardware) Reset() {
	*x = CPUHardware{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUHardware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUHardware) ProtoMessage() {}

func (x *CPUHardware) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUHardware.ProtoReflect.Descriptor instead.
func (*CPUHardware) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{8}
}

func (x *CPUHardware) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CPUHardware) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPUHardware) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *CPUHardware) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *CPUHardware) GetCache() int64 {
	if x != nil {
		return x.Cache
	}
	return 0
}

func (x *CPUHardware) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type MemoryHardware struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"` // 改名: total -> size
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Frequency     float64                `protobuf:"fixed64,3,opt,name=frequency,proto3" json:"frequency,omitempty"` // 移除 channels 字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryHardware) Reset() {
	*x = MemoryHardware{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryHardware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryHardware) ProtoMessage() {}

func (x *MemoryHardware) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryHardware.ProtoReflect.Descriptor instead.
func (*MemoryHardware) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{9}
}

func (x *MemoryHardware) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MemoryHardware) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MemoryHardware) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type GPUHardware struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	MemoryTotal       int64                  `protobuf:"varint,2,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	Architecture      string                 `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`                                    // 新增架构字段
	DriverVersion     string                 `protobuf:"bytes,4,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`             // 新增驱动版本字段
	ComputeCapability string                 `protobuf:"bytes,5,opt,name=compute_capability,json=computeCapability,proto3" json:"compute_capability,omitempty"` // 新增计算能力字段
	Tdp               int32                  `protobuf:"varint,6,opt,name=tdp,proto3" json:"tdp,omitempty"`                                                     // 新增功耗指标字段
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GPUHardware) Reset() {
	*x = GPUHardware{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUHardware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUHardware) ProtoMessage() {}

func (x *GPUHardware) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUHardware.ProtoReflect.Descriptor instead.
func (*GPUHardware) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{10}
}

func (x *GPUHardware) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUHardware) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *GPUHardware) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *GPUHardware) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *GPUHardware) GetComputeCapability() string {
	if x != nil {
		return x.ComputeCapability
	}
	return ""
}

func (x *GPUHardware) GetTdp() int32 {
	if x != nil {
		return x.Tdp
	}
	return 0
}

type StorageDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"` // 新增型号字段
	Capacity      int64                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"` // 新增挂载路径字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDevice) Reset() {
	*x = StorageDevice{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDevice) ProtoMessage() {}

func (x *StorageDevice) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDevice.ProtoReflect.Descriptor instead.
func (*StorageDevice) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{11}
}

func (x *StorageDevice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StorageDevice) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StorageDevice) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StorageDevice) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// 添加 NetworkDevice 消息体
type NetworkDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // 网卡名称
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"` // MAC地址
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`    // IP地址
	Speed         int64                  `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`                            // 网卡速率(Mbps)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkDevice) Reset() {
	*x = NetworkDevice{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDevice) ProtoMessage() {}

func (x *NetworkDevice) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkDevice.ProtoReflect.Descriptor instead.
func (*NetworkDevice) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkDevice) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkDevice) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NetworkDevice) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

// 添加MetricsInfo消息体 - 重构为扁平结构
type MetricsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpus          []*CPUMetrics          `protobuf:"bytes,1,rep,name=cpus,proto3" json:"cpus,omitempty"` // 改为CPU指标数组
	Memory        *MemoryMetrics         `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpus          []*GPUMetrics          `protobuf:"bytes,3,rep,name=gpus,proto3" json:"gpus,omitempty"` // 改为GPU指标数组
	Storages      []*StorageMetrics      `protobuf:"bytes,4,rep,name=storages,proto3" json:"storages,omitempty"`
	Network       *NetworkMetrics        `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsInfo) Reset() {
	*x = MetricsInfo{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsInfo) ProtoMessage() {}

func (x *MetricsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsInfo.ProtoReflect.Descriptor instead.
func (*MetricsInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{13}
}

func (x *MetricsInfo) GetCpus() []*CPUMetrics {
	if x != nil {
		return x.Cpus
	}
	return nil
}

func (x *MetricsInfo) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *MetricsInfo) GetGpus() []*GPUMetrics {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *MetricsInfo) GetStorages() []*StorageMetrics {
	if x != nil {
		return x.Storages
	}
	return nil
}

func (x *MetricsInfo) GetNetwork() *NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

type CPUMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`      // 新增型号字段
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`     // 新增核心数字段
	Threads       int32                  `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"` // 新增线程数字段
	Usage         float64                `protobuf:"fixed64,4,opt,name=usage,proto3" json:"usage,omitempty"`    // CPU使用率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUMetrics) Reset() {
	*x = CPUMetrics{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUMetrics) ProtoMessage() {}

func (x *CPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUMetrics.ProtoReflect.Descriptor instead.
func (*CPUMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{14}
}

func (x *CPUMetrics) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CPUMetrics) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPUMetrics) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *CPUMetrics) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

type MemoryMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`         // 总内存大小
	Available     int64                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"` // 可用内存大小
	Used          int64                  `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`           // 新增已用内存字段
	Usage         float64                `protobuf:"fixed64,4,opt,name=usage,proto3" json:"usage,omitempty"`        // 新增使用率字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{15}
}

func (x *MemoryMetrics) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryMetrics) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *MemoryMetrics) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemoryMetrics) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

type GPUMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                                  // 新增GPU型号字段
	MemoryTotal   int64                  `protobuf:"varint,2,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`  // 显存总量
	Usage         float64                `protobuf:"fixed64,3,opt,name=usage,proto3" json:"usage,omitempty"`                                // GPU使用率
	MemoryUsed    int64                  `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`     // 已用显存
	MemoryFree    int64                  `protobuf:"varint,5,opt,name=memory_free,json=memoryFree,proto3" json:"memory_free,omitempty"`     // 新增可用显存字段
	MemoryUsage   float64                `protobuf:"fixed64,6,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // 新增显存使用率字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUMetrics) Reset() {
	*x = GPUMetrics{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMetrics) ProtoMessage() {}

func (x *GPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMetrics.ProtoReflect.Descriptor instead.
func (*GPUMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{16}
}

func (x *GPUMetrics) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUMetrics) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *GPUMetrics) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *GPUMetrics) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *GPUMetrics) GetMemoryFree() int64 {
	if x != nil {
		return x.MemoryFree
	}
	return 0
}

func (x *GPUMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

type StorageMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`          // 新增挂载路径字段
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`          // 新增存储类型字段
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`        // 新增设备型号字段
	Capacity      int64                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"` // 新增总容量字段
	Used          int64                  `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`         // 新增已用空间字段
	Free          int64                  `protobuf:"varint,6,opt,name=free,proto3" json:"free,omitempty"`         // 新增可用空间字段
	Usage         float64                `protobuf:"fixed64,7,opt,name=usage,proto3" json:"usage,omitempty"`      // 存储使用率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageMetrics) Reset() {
	*x = StorageMetrics{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageMetrics) ProtoMessage() {}

func (x *StorageMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageMetrics.ProtoReflect.Descriptor instead.
func (*StorageMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{17}
}

func (x *StorageMetrics) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StorageMetrics) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StorageMetrics) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StorageMetrics) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StorageMetrics) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *StorageMetrics) GetFree() int64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *StorageMetrics) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

type NetworkMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InboundTraffic  float64                `protobuf:"fixed64,1,opt,name=inbound_traffic,json=inboundTraffic,proto3" json:"inbound_traffic,omitempty"`    // 改名: rx_rate -> inbound_traffic
	OutboundTraffic float64                `protobuf:"fixed64,2,opt,name=outbound_traffic,json=outboundTraffic,proto3" json:"outbound_traffic,omitempty"` // 改名: tx_rate -> outbound_traffic
	Connections     int32                  `protobuf:"varint,3,opt,name=connections,proto3" json:"connections,omitempty"`                                 // 连接数
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{18}
}

func (x *NetworkMetrics) GetInboundTraffic() float64 {
	if x != nil {
		return x.InboundTraffic
	}
	return 0
}

func (x *NetworkMetrics) GetOutboundTraffic() float64 {
	if x != nil {
		return x.OutboundTraffic
	}
	return 0
}

func (x *NetworkMetrics) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

// Pipeline 执行请求
type ExecutePipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	PipelineData  []byte                 `protobuf:"bytes,3,opt,name=pipeline_data,json=pipelineData,proto3" json:"pipeline_data,omitempty"`
	Envs          map[string]string      `protobuf:"bytes,4,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Args          map[string]string      `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePipelineRequest) Reset() {
	*x = ExecutePipelineRequest{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePipelineRequest) ProtoMessage() {}

func (x *ExecutePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePipelineRequest.ProtoReflect.Descriptor instead.
func (*ExecutePipelineRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{19}
}

func (x *ExecutePipelineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecutePipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ExecutePipelineRequest) GetPipelineData() []byte {
	if x != nil {
		return x.PipelineData
	}
	return nil
}

func (x *ExecutePipelineRequest) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *ExecutePipelineRequest) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ExecutePipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePipelineResponse) Reset() {
	*x = ExecutePipelineResponse{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePipelineResponse) ProtoMessage() {}

func (x *ExecutePipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePipelineResponse.ProtoReflect.Descriptor instead.
func (*ExecutePipelineResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{20}
}

func (x *ExecutePipelineResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutePipelineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Pipeline 状态更新
type PipelineStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep   int32                  `protobuf:"varint,4,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Progress      float32                `protobuf:"fixed32,5,opt,name=progress,proto3" json:"progress,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineStatusUpdate) Reset() {
	*x = PipelineStatusUpdate{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStatusUpdate) ProtoMessage() {}

func (x *PipelineStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStatusUpdate.ProtoReflect.Descriptor instead.
func (*PipelineStatusUpdate) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{21}
}

func (x *PipelineStatusUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineStatusUpdate) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineStatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PipelineStatusUpdate) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *PipelineStatusUpdate) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *PipelineStatusUpdate) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PipelineStatusUpdate) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// Step 状态更新
type StepStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Status        StepStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=gamenode.StepStatus" json:"status,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Logs          []byte                 `protobuf:"bytes,7,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStatusUpdate) Reset() {
	*x = StepStatusUpdate{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStatusUpdate) ProtoMessage() {}

func (x *StepStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStatusUpdate.ProtoReflect.Descriptor instead.
func (*StepStatusUpdate) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{22}
}

func (x *StepStatusUpdate) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *StepStatusUpdate) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepStatusUpdate) GetStatus() StepStatus {
	if x != nil {
		return x.Status
	}
	return StepStatus_PENDING
}

func (x *StepStatusUpdate) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *StepStatusUpdate) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *StepStatusUpdate) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StepStatusUpdate) GetLogs() []byte {
	if x != nil {
		return x.Logs
	}
	return nil
}

// Pipeline 取消请求
type PipelineCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCancelRequest) Reset() {
	*x = PipelineCancelRequest{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCancelRequest) ProtoMessage() {}

func (x *PipelineCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCancelRequest.ProtoReflect.Descriptor instead.
func (*PipelineCancelRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{23}
}

func (x *PipelineCancelRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineCancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{24}
}

func (x *CancelResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 日志请求
type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{25}
}

func (x *LogRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *LogRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *LogRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 日志条目
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{26}
}

func (x *LogEntry) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *LogEntry) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 通用响应
type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{28}
}

func (x *ReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 事件
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          map[string]string      `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{29}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Event) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// 添加SystemInfo消息体
type SystemInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OsDistribution       string                 `protobuf:"bytes,1,opt,name=os_distribution,json=osDistribution,proto3" json:"os_distribution,omitempty"`                       // 操作系统发行版
	OsVersion            string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`                                      // 操作系统版本
	OsArchitecture       string                 `protobuf:"bytes,3,opt,name=os_architecture,json=osArchitecture,proto3" json:"os_architecture,omitempty"`                       // 操作系统架构
	KernelVersion        string                 `protobuf:"bytes,4,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`                          // 内核版本
	GpuDriverVersion     string                 `protobuf:"bytes,5,opt,name=gpu_driver_version,json=gpuDriverVersion,proto3" json:"gpu_driver_version,omitempty"`               // GPU驱动版本
	GpuComputeApiVersion string                 `protobuf:"bytes,6,opt,name=gpu_compute_api_version,json=gpuComputeApiVersion,proto3" json:"gpu_compute_api_version,omitempty"` // GPU计算框架版本(CUDA/ROCm/oneAPI/OpenCL)
	DockerVersion        string                 `protobuf:"bytes,7,opt,name=docker_version,json=dockerVersion,proto3" json:"docker_version,omitempty"`                          // Docker版本
	ContainerdVersion    string                 `protobuf:"bytes,8,opt,name=containerd_version,json=containerdVersion,proto3" json:"containerd_version,omitempty"`              // Containerd版本
	RuncVersion          string                 `protobuf:"bytes,9,opt,name=runc_version,json=runcVersion,proto3" json:"runc_version,omitempty"`                                // Runc版本
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{30}
}

func (x *SystemInfo) GetOsDistribution() string {
	if x != nil {
		return x.OsDistribution
	}
	return ""
}

func (x *SystemInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SystemInfo) GetOsArchitecture() string {
	if x != nil {
		return x.OsArchitecture
	}
	return ""
}

func (x *SystemInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SystemInfo) GetGpuDriverVersion() string {
	if x != nil {
		return x.GpuDriverVersion
	}
	return ""
}

func (x *SystemInfo) GetGpuComputeApiVersion() string {
	if x != nil {
		return x.GpuComputeApiVersion
	}
	return ""
}

func (x *SystemInfo) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

func (x *SystemInfo) GetContainerdVersion() string {
	if x != nil {
		return x.ContainerdVersion
	}
	return ""
}

func (x *SystemInfo) GetRuncVersion() string {
	if x != nil {
		return x.RuncVersion
	}
	return ""
}

// 添加GameNodeStatus消息体
type GameNodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         GameNodeState          `protobuf:"varint,1,opt,name=state,proto3,enum=gamenode.GameNodeState" json:"state,omitempty"` // 节点状态
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`                           // 是否在线
	LastOnline    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_online,json=lastOnline,proto3" json:"last_online,omitempty"`  // 最后在线时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`     // 状态更新时间
	Hardware      *HardwareInfo          `protobuf:"bytes,5,opt,name=hardware,proto3" json:"hardware,omitempty"`                        // 硬件配置
	System        *SystemInfo            `protobuf:"bytes,6,opt,name=system,proto3" json:"system,omitempty"`                            // 系统配置
	Metrics       *MetricsInfo           `protobuf:"bytes,7,opt,name=metrics,proto3" json:"metrics,omitempty"`                          // 监控指标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameNodeStatus) Reset() {
	*x = GameNodeStatus{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameNodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameNodeStatus) ProtoMessage() {}

func (x *GameNodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameNodeStatus.ProtoReflect.Descriptor instead.
func (*GameNodeStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{31}
}

func (x *GameNodeStatus) GetState() GameNodeState {
	if x != nil {
		return x.State
	}
	return GameNodeState_NODE_STATE_OFFLINE
}

func (x *GameNodeStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *GameNodeStatus) GetLastOnline() *timestamppb.Timestamp {
	if x != nil {
		return x.LastOnline
	}
	return nil
}

func (x *GameNodeStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GameNodeStatus) GetHardware() *HardwareInfo {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *GameNodeStatus) GetSystem() *SystemInfo {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *GameNodeStatus) GetMetrics() *MetricsInfo {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// 添加完整的GameNode消息体
type GameNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // 节点ID
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`                                                                                 // 节点别名
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                                                                                 // 节点型号
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                                                                   // 节点类型
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`                                                                           // 节点位置
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`     // 标签
	Hardware      map[string]string      `protobuf:"bytes,7,rep,name=hardware,proto3" json:"hardware,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 硬件配置(简化版)
	System        map[string]string      `protobuf:"bytes,8,rep,name=system,proto3" json:"system,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`     // 系统配置(简化版)
	Status        *GameNodeStatus        `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                                                                               // 节点状态信息
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                       // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                       // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameNode) Reset() {
	*x = GameNode{}
	mi := &file_internal_proto_gamenode_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameNode) ProtoMessage() {}

func (x *GameNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gamenode_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameNode.ProtoReflect.Descriptor instead.
func (*GameNode) Descriptor() ([]byte, []int) {
	return file_internal_proto_gamenode_proto_rawDescGZIP(), []int{32}
}

func (x *GameNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameNode) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *GameNode) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GameNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GameNode) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GameNode) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GameNode) GetHardware() map[string]string {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *GameNode) GetSystem() map[string]string {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *GameNode) GetStatus() *GameNodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GameNode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GameNode) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_internal_proto_gamenode_proto protoreflect.FileDescriptor

const file_internal_proto_gamenode_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/gamenode.proto\x12\bgamenode\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x04\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12C\n" +
	"\bhardware\x18\x06 \x03(\v2'.gamenode.RegisterRequest.HardwareEntryR\bhardware\x12=\n" +
	"\x06system\x18\a \x03(\v2%.gamenode.RegisterRequest.SystemEntryR\x06system\x12=\n" +
	"\x06labels\x18\b \x03(\v2%.gamenode.RegisterRequest.LabelsEntryR\x06labels\x12;\n" +
	"\rhardware_info\x18\t \x01(\v2\x16.gamenode.HardwareInfoR\fhardwareInfo\x125\n" +
	"\vsystem_info\x18\n" +
	" \x01(\v2\x14.gamenode.SystemInfoR\n" +
	"systemInfo\x1a;\n" +
	"\rHardwareEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vSystemEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x91\x01\n" +
	"\x10HeartbeatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x120\n" +
	"\x06status\x18\x04 \x01(\v2\x18.gamenode.GameNodeStatusR\x06status\"E\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"i\n" +
	"\rMetricsReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12*\n" +
	"\ametrics\x18\x03 \x03(\v2\x10.gamenode.MetricR\ametrics\"\xb7\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x124\n" +
	"\x06labels\x18\x04 \x03(\v2\x1c.gamenode.Metric.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x02\n" +
	"\fResourceInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x126\n" +
	"\n" +
	"node_state\x18\x03 \x01(\x0e2\x17.gamenode.GameNodeStateR\tnodeState\x12/\n" +
	"\tnode_type\x18\x04 \x01(\x0e2\x12.gamenode.NodeTypeR\bnodeType\x122\n" +
	"\bhardware\x18\x05 \x01(\v2\x16.gamenode.HardwareInfoR\bhardware\x12,\n" +
	"\x06system\x18\x06 \x01(\v2\x14.gamenode.SystemInfoR\x06system\x12/\n" +
	"\ametrics\x18\a \x01(\v2\x15.gamenode.MetricsInfoR\ametrics\"\x84\x02\n" +
	"\fHardwareInfo\x12)\n" +
	"\x04cpus\x18\x01 \x03(\v2\x15.gamenode.CPUHardwareR\x04cpus\x124\n" +
	"\bmemories\x18\x02 \x03(\v2\x18.gamenode.MemoryHardwareR\bmemories\x12)\n" +
	"\x04gpus\x18\x03 \x03(\v2\x15.gamenode.GPUHardwareR\x04gpus\x123\n" +
	"\bstorages\x18\x04 \x03(\v2\x17.gamenode.StorageDeviceR\bstorages\x123\n" +
	"\bnetworks\x18\x05 \x03(\v2\x17.gamenode.NetworkDeviceR\bnetworks\"\xab\x01\n" +
	"\vCPUHardware\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x05R\athreads\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\x01R\tfrequency\x12\x14\n" +
	"\x05cache\x18\x05 \x01(\x03R\x05cache\x12\"\n" +
	"\farchitecture\x18\x06 \x01(\tR\farchitecture\"V\n" +
	"\x0eMemoryHardware\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\tfrequency\x18\x03 \x01(\x01R\tfrequency\"\xd2\x01\n" +
	"\vGPUHardware\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12!\n" +
	"\fmemory_total\x18\x02 \x01(\x03R\vmemoryTotal\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x12%\n" +
	"\x0edriver_version\x18\x04 \x01(\tR\rdriverVersion\x12-\n" +
	"\x12compute_capability\x18\x05 \x01(\tR\x11computeCapability\x12\x10\n" +
	"\x03tdp\x18\x06 \x01(\x05R\x03tdp\"i\n" +
	"\rStorageDevice\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x03R\bcapacity\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"y\n" +
	"\rNetworkDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x03R\x05speed\"\xfc\x01\n" +
	"\vMetricsInfo\x12(\n" +
	"\x04cpus\x18\x01 \x03(\v2\x14.gamenode.CPUMetricsR\x04cpus\x12/\n" +
	"\x06memory\x18\x02 \x01(\v2\x17.gamenode.MemoryMetricsR\x06memory\x12(\n" +
	"\x04gpus\x18\x03 \x03(\v2\x14.gamenode.GPUMetricsR\x04gpus\x124\n" +
	"\bstorages\x18\x04 \x03(\v2\x18.gamenode.StorageMetricsR\bstorages\x122\n" +
	"\anetwork\x18\x05 \x01(\v2\x18.gamenode.NetworkMetricsR\anetwork\"h\n" +
	"\n" +
	"CPUMetrics\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x05R\athreads\x12\x14\n" +
	"\x05usage\x18\x04 \x01(\x01R\x05usage\"m\n" +
	"\rMemoryMetrics\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x03R\tavailable\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x03R\x04used\x12\x14\n" +
	"\x05usage\x18\x04 \x01(\x01R\x05usage\"\xc0\x01\n" +
	"\n" +
	"GPUMetrics\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12!\n" +
	"\fmemory_total\x18\x02 \x01(\x03R\vmemoryTotal\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\x01R\x05usage\x12\x1f\n" +
	"\vmemory_used\x18\x04 \x01(\x03R\n" +
	"memoryUsed\x12\x1f\n" +
	"\vmemory_free\x18\x05 \x01(\x03R\n" +
	"memoryFree\x12!\n" +
	"\fmemory_usage\x18\x06 \x01(\x01R\vmemoryUsage\"\xa8\x01\n" +
	"\x0eStorageMetrics\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x03R\bcapacity\x12\x12\n" +
	"\x04used\x18\x05 \x01(\x03R\x04used\x12\x12\n" +
	"\x04free\x18\x06 \x01(\x03R\x04free\x12\x14\n" +
	"\x05usage\x18\a \x01(\x01R\x05usage\"\x86\x01\n" +
	"\x0eNetworkMetrics\x12'\n" +
	"\x0finbound_traffic\x18\x01 \x01(\x01R\x0einboundTraffic\x12)\n" +
	"\x10outbound_traffic\x18\x02 \x01(\x01R\x0foutboundTraffic\x12 \n" +
	"\vconnections\x18\x03 \x01(\x05R\vconnections\"\xe0\x02\n" +
	"\x16ExecutePipelineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12#\n" +
	"\rpipeline_data\x18\x03 \x01(\fR\fpipelineData\x12>\n" +
	"\x04envs\x18\x04 \x03(\v2*.gamenode.ExecutePipelineRequest.EnvsEntryR\x04envs\x12>\n" +
	"\x04args\x18\x05 \x03(\v2*.gamenode.ExecutePipelineRequest.ArgsEntryR\x04args\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x17ExecutePipelineResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x80\x02\n" +
	"\x14PipelineStatusUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x04 \x01(\x05R\vcurrentStep\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x02R\bprogress\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xed\x01\n" +
	"\x10StepStatusUpdate\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.gamenode.StepStatusR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04logs\x18\a \x01(\fR\x04logs\"P\n" +
	"\x15PipelineCancelRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"B\n" +
	"\x0eCancelResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x96\x01\n" +
	"\n" +
	"LogRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\"\xae\x01\n" +
	"\bLogEntry\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"B\n" +
	"\x0eUpdateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x0eReportResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9c\x02\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12-\n" +
	"\x04data\x18\a \x03(\v2\x19.gamenode.Event.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x03\n" +
	"\n" +
	"SystemInfo\x12'\n" +
	"\x0fos_distribution\x18\x01 \x01(\tR\x0eosDistribution\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12'\n" +
	"\x0fos_architecture\x18\x03 \x01(\tR\x0eosArchitecture\x12%\n" +
	"\x0ekernel_version\x18\x04 \x01(\tR\rkernelVersion\x12,\n" +
	"\x12gpu_driver_version\x18\x05 \x01(\tR\x10gpuDriverVersion\x125\n" +
	"\x17gpu_compute_api_version\x18\x06 \x01(\tR\x14gpuComputeApiVersion\x12%\n" +
	"\x0edocker_version\x18\a \x01(\tR\rdockerVersion\x12-\n" +
	"\x12containerd_version\x18\b \x01(\tR\x11containerdVersion\x12!\n" +
	"\frunc_version\x18\t \x01(\tR\vruncVersion\"\xe2\x02\n" +
	"\x0eGameNodeStatus\x12-\n" +
	"\x05state\x18\x01 \x01(\x0e2\x17.gamenode.GameNodeStateR\x05state\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12;\n" +
	"\vlast_online\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastOnline\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x122\n" +
	"\bhardware\x18\x05 \x01(\v2\x16.gamenode.HardwareInfoR\bhardware\x12,\n" +
	"\x06system\x18\x06 \x01(\v2\x14.gamenode.SystemInfoR\x06system\x12/\n" +
	"\ametrics\x18\a \x01(\v2\x15.gamenode.MetricsInfoR\ametrics\"\xff\x04\n" +
	"\bGameNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x126\n" +
	"\x06labels\x18\x06 \x03(\v2\x1e.gamenode.GameNode.LabelsEntryR\x06labels\x12<\n" +
	"\bhardware\x18\a \x03(\v2 .gamenode.GameNode.HardwareEntryR\bhardware\x126\n" +
	"\x06system\x18\b \x03(\v2\x1e.gamenode.GameNode.SystemEntryR\x06system\x120\n" +
	"\x06status\x18\t \x01(\v2\x18.gamenode.GameNodeStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rHardwareEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vSystemEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*P\n" +
	"\n" +
	"StepStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04*i\n" +
	"\bNodeType\x12\x15\n" +
	"\x11NODE_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12NODE_TYPE_PHYSICAL\x10\x01\x12\x15\n" +
	"\x11NODE_TYPE_VIRTUAL\x10\x02\x12\x17\n" +
	"\x13NODE_TYPE_CONTAINER\x10\x03*\x9b\x01\n" +
	"\rGameNodeState\x12\x16\n" +
	"\x12NODE_STATE_OFFLINE\x10\x00\x12\x15\n" +
	"\x11NODE_STATE_ONLINE\x10\x01\x12\x1a\n" +
	"\x16NODE_STATE_MAINTENANCE\x10\x02\x12\x14\n" +
	"\x10NODE_STATE_READY\x10\x03\x12\x13\n" +
	"\x0fNODE_STATE_BUSY\x10\x04\x12\x14\n" +
	"\x10NODE_STATE_ERROR\x10\x052\xa5\x05\n" +
	"\x13GameNodeGRPCService\x12A\n" +
	"\bRegister\x12\x19.gamenode.RegisterRequest\x1a\x1a.gamenode.RegisterResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.gamenode.HeartbeatRequest\x1a\x1b.gamenode.HeartbeatResponse\x12B\n" +
	"\rReportMetrics\x12\x17.gamenode.MetricsReport\x1a\x18.gamenode.ReportResponse\x12F\n" +
	"\x12UpdateResourceInfo\x12\x16.gamenode.ResourceInfo\x1a\x18.gamenode.UpdateResponse\x12V\n" +
	"\x0fExecutePipeline\x12 .gamenode.ExecutePipelineRequest\x1a!.gamenode.ExecutePipelineResponse\x12P\n" +
	"\x14UpdatePipelineStatus\x12\x1e.gamenode.PipelineStatusUpdate\x1a\x18.gamenode.UpdateResponse\x12H\n" +
	"\x10UpdateStepStatus\x12\x1a.gamenode.StepStatusUpdate\x1a\x18.gamenode.UpdateResponse\x12K\n" +
	"\x0eCancelPipeline\x12\x1f.gamenode.PipelineCancelRequest\x1a\x18.gamenode.CancelResponse\x128\n" +
	"\n" +
	"StreamLogs\x12\x14.gamenode.LogRequest\x1a\x12.gamenode.LogEntry0\x01B8Z6github.com/open-beagle/beagle-wind-game/internal/protob\x06proto3"

var (
	file_internal_proto_gamenode_proto_rawDescOnce sync.Once
	file_internal_proto_gamenode_proto_rawDescData []byte
)

func file_internal_proto_gamenode_proto_rawDescGZIP() []byte {
	file_internal_proto_gamenode_proto_rawDescOnce.Do(func() {
		file_internal_proto_gamenode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_gamenode_proto_rawDesc), len(file_internal_proto_gamenode_proto_rawDesc)))
	})
	return file_internal_proto_gamenode_proto_rawDescData
}

var file_internal_proto_gamenode_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_proto_gamenode_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_internal_proto_gamenode_proto_goTypes = []any{
	(StepStatus)(0),                 // 0: gamenode.StepStatus
	(NodeType)(0),                   // 1: gamenode.NodeType
	(GameNodeState)(0),              // 2: gamenode.GameNodeState
	(*RegisterRequest)(nil),         // 3: gamenode.RegisterRequest
	(*RegisterResponse)(nil),        // 4: gamenode.RegisterResponse
	(*HeartbeatRequest)(nil),        // 5: gamenode.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 6: gamenode.HeartbeatResponse
	(*MetricsReport)(nil),           // 7: gamenode.MetricsReport
	(*Metric)(nil),                  // 8: gamenode.Metric
	(*ResourceInfo)(nil),            // 9: gamenode.ResourceInfo
	(*HardwareInfo)(nil),            // 10: gamenode.HardwareInfo
	(*CPUHardware)(nil),             // 11: gamenode.CPUHardware
	(*MemoryHardware)(nil),          // 12: gamenode.MemoryHardware
	(*GPUHardware)(nil),             // 13: gamenode.GPUHardware
	(*StorageDevice)(nil),           // 14: gamenode.StorageDevice
	(*NetworkDevice)(nil),           // 15: gamenode.NetworkDevice
	(*MetricsInfo)(nil),             // 16: gamenode.MetricsInfo
	(*CPUMetrics)(nil),              // 17: gamenode.CPUMetrics
	(*MemoryMetrics)(nil),           // 18: gamenode.MemoryMetrics
	(*GPUMetrics)(nil),              // 19: gamenode.GPUMetrics
	(*StorageMetrics)(nil),          // 20: gamenode.StorageMetrics
	(*NetworkMetrics)(nil),          // 21: gamenode.NetworkMetrics
	(*ExecutePipelineRequest)(nil),  // 22: gamenode.ExecutePipelineRequest
	(*ExecutePipelineResponse)(nil), // 23: gamenode.ExecutePipelineResponse
	(*PipelineStatusUpdate)(nil),    // 24: gamenode.PipelineStatusUpdate
	(*StepStatusUpdate)(nil),        // 25: gamenode.StepStatusUpdate
	(*PipelineCancelRequest)(nil),   // 26: gamenode.PipelineCancelRequest
	(*CancelResponse)(nil),          // 27: gamenode.CancelResponse
	(*LogRequest)(nil),              // 28: gamenode.LogRequest
	(*LogEntry)(nil),                // 29: gamenode.LogEntry
	(*UpdateResponse)(nil),          // 30: gamenode.UpdateResponse
	(*ReportResponse)(nil),          // 31: gamenode.ReportResponse
	(*Event)(nil),                   // 32: gamenode.Event
	(*SystemInfo)(nil),              // 33: gamenode.SystemInfo
	(*GameNodeStatus)(nil),          // 34: gamenode.GameNodeStatus
	(*GameNode)(nil),                // 35: gamenode.GameNode
	nil,                             // 36: gamenode.RegisterRequest.HardwareEntry
	nil,                             // 37: gamenode.RegisterRequest.SystemEntry
	nil,                             // 38: gamenode.RegisterRequest.LabelsEntry
	nil,                             // 39: gamenode.Metric.LabelsEntry
	nil,                             // 40: gamenode.ExecutePipelineRequest.EnvsEntry
	nil,                             // 41: gamenode.ExecutePipelineRequest.ArgsEntry
	nil,                             // 42: gamenode.Event.DataEntry
	nil,                             // 43: gamenode.GameNode.LabelsEntry
	nil,                             // 44: gamenode.GameNode.HardwareEntry
	nil,                             // 45: gamenode.GameNode.SystemEntry
	(*timestamppb.Timestamp)(nil),   // 46: google.protobuf.Timestamp
}
var file_internal_proto_gamenode_proto_depIdxs = []int32{
	36, // 0: gamenode.RegisterRequest.hardware:type_name -> gamenode.RegisterRequest.HardwareEntry
	37, // 1: gamenode.RegisterRequest.system:type_name -> gamenode.RegisterRequest.SystemEntry
	38, // 2: gamenode.RegisterRequest.labels:type_name -> gamenode.RegisterRequest.LabelsEntry
	10, // 3: gamenode.RegisterRequest.hardware_info:type_name -> gamenode.HardwareInfo
	33, // 4: gamenode.RegisterRequest.system_info:type_name -> gamenode.SystemInfo
	34, // 5: gamenode.HeartbeatRequest.status:type_name -> gamenode.GameNodeStatus
	8,  // 6: gamenode.MetricsReport.metrics:type_name -> gamenode.Metric
	39, // 7: gamenode.Metric.labels:type_name -> gamenode.Metric.LabelsEntry
	2,  // 8: gamenode.ResourceInfo.node_state:type_name -> gamenode.GameNodeState
	1,  // 9: gamenode.ResourceInfo.node_type:type_name -> gamenode.NodeType
	10, // 10: gamenode.ResourceInfo.hardware:type_name -> gamenode.HardwareInfo
	33, // 11: gamenode.ResourceInfo.system:type_name -> gamenode.SystemInfo
	16, // 12: gamenode.ResourceInfo.metrics:type_name -> gamenode.MetricsInfo
	11, // 13: gamenode.HardwareInfo.cpus:type_name -> gamenode.CPUHardware
	12, // 14: gamenode.HardwareInfo.memories:type_name -> gamenode.MemoryHardware
	13, // 15: gamenode.HardwareInfo.gpus:type_name -> gamenode.GPUHardware
	14, // 16: gamenode.HardwareInfo.storages:type_name -> gamenode.StorageDevice
	15, // 17: gamenode.HardwareInfo.networks:type_name -> gamenode.NetworkDevice
	17, // 18: gamenode.MetricsInfo.cpus:type_name -> gamenode.CPUMetrics
	18, // 19: gamenode.MetricsInfo.memory:type_name -> gamenode.MemoryMetrics
	19, // 20: gamenode.MetricsInfo.gpus:type_name -> gamenode.GPUMetrics
	20, // 21: gamenode.MetricsInfo.storages:type_name -> gamenode.StorageMetrics
	21, // 22: gamenode.MetricsInfo.network:type_name -> gamenode.NetworkMetrics
	40, // 23: gamenode.ExecutePipelineRequest.envs:type_name -> gamenode.ExecutePipelineRequest.EnvsEntry
	41, // 24: gamenode.ExecutePipelineRequest.args:type_name -> gamenode.ExecutePipelineRequest.ArgsEntry
	46, // 25: gamenode.PipelineStatusUpdate.update_time:type_name -> google.protobuf.Timestamp
	0,  // 26: gamenode.StepStatusUpdate.status:type_name -> gamenode.StepStatus
	46, // 27: gamenode.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	46, // 28: gamenode.Event.timestamp:type_name -> google.protobuf.Timestamp
	42, // 29: gamenode.Event.data:type_name -> gamenode.Event.DataEntry
	2,  // 30: gamenode.GameNodeStatus.state:type_name -> gamenode.GameNodeState
	46, // 31: gamenode.GameNodeStatus.last_online:type_name -> google.protobuf.Timestamp
	46, // 32: gamenode.GameNodeStatus.updated_at:type_name -> google.protobuf.Timestamp
	10, // 33: gamenode.GameNodeStatus.hardware:type_name -> gamenode.HardwareInfo
	33, // 34: gamenode.GameNodeStatus.system:type_name -> gamenode.SystemInfo
	16, // 35: gamenode.GameNodeStatus.metrics:type_name -> gamenode.MetricsInfo
	43, // 36: gamenode.GameNode.labels:type_name -> gamenode.GameNode.LabelsEntry
	44, // 37: gamenode.GameNode.hardware:type_name -> gamenode.GameNode.HardwareEntry
	45, // 38: gamenode.GameNode.system:type_name -> gamenode.GameNode.SystemEntry
	34, // 39: gamenode.GameNode.status:type_name -> gamenode.GameNodeStatus
	46, // 40: gamenode.GameNode.created_at:type_name -> google.protobuf.Timestamp
	46, // 41: gamenode.GameNode.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 42: gamenode.GameNodeGRPCService.Register:input_type -> gamenode.RegisterRequest
	5,  // 43: gamenode.GameNodeGRPCService.Heartbeat:input_type -> gamenode.HeartbeatRequest
	7,  // 44: gamenode.GameNodeGRPCService.ReportMetrics:input_type -> gamenode.MetricsReport
	9,  // 45: gamenode.GameNodeGRPCService.UpdateResourceInfo:input_type -> gamenode.ResourceInfo
	22, // 46: gamenode.GameNodeGRPCService.ExecutePipeline:input_type -> gamenode.ExecutePipelineRequest
	24, // 47: gamenode.GameNodeGRPCService.UpdatePipelineStatus:input_type -> gamenode.PipelineStatusUpdate
	25, // 48: gamenode.GameNodeGRPCService.UpdateStepStatus:input_type -> gamenode.StepStatusUpdate
	26, // 49: gamenode.GameNodeGRPCService.CancelPipeline:input_type -> gamenode.PipelineCancelRequest
	28, // 50: gamenode.GameNodeGRPCService.StreamLogs:input_type -> gamenode.LogRequest
	4,  // 51: gamenode.GameNodeGRPCService.Register:output_type -> gamenode.RegisterResponse
	6,  // 52: gamenode.GameNodeGRPCService.Heartbeat:output_type -> gamenode.HeartbeatResponse
	31, // 53: gamenode.GameNodeGRPCService.ReportMetrics:output_type -> gamenode.ReportResponse
	30, // 54: gamenode.GameNodeGRPCService.UpdateResourceInfo:output_type -> gamenode.UpdateResponse
	23, // 55: gamenode.GameNodeGRPCService.ExecutePipeline:output_type -> gamenode.ExecutePipelineResponse
	30, // 56: gamenode.GameNodeGRPCService.UpdatePipelineStatus:output_type -> gamenode.UpdateResponse
	30, // 57: gamenode.GameNodeGRPCService.UpdateStepStatus:output_type -> gamenode.UpdateResponse
	27, // 58: gamenode.GameNodeGRPCService.CancelPipeline:output_type -> gamenode.CancelResponse
	29, // 59: gamenode.GameNodeGRPCService.StreamLogs:output_type -> gamenode.LogEntry
	51, // [51:60] is the sub-list for method output_type
	42, // [42:51] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_internal_proto_gamenode_proto_init() }
func file_internal_proto_gamenode_proto_init() {
	if File_internal_proto_gamenode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_gamenode_proto_rawDesc), len(file_internal_proto_gamenode_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gamenode_proto_goTypes,
		DependencyIndexes: file_internal_proto_gamenode_proto_depIdxs,
		EnumInfos:         file_internal_proto_gamenode_proto_enumTypes,
		MessageInfos:      file_internal_proto_gamenode_proto_msgTypes,
	}.Build()
	File_internal_proto_gamenode_proto = out.File
	file_internal_proto_gamenode_proto_goTypes = nil
	file_internal_proto_gamenode_proto_depIdxs = nil
}
