name: Platform Start

envs:
  S3_ACCESS_KEY: "S3_ACCESS_KEY"
  S3_SECRET_KEY: "S3_SECRET_KEY"
  S3_BUCKET: "S3_BUCKET"
  S3_URL: "S3_URL"

args:
  - name: "platform_name"
    type: "string"
    required: true
    default: "platform"

steps:
  - name: "upload_data"
    image: "your_image_name"
    command: "your_command"
    volumes:
      - name: "data_volume"
        path: "/data/input"

  - name: "download_data"
    image: "your_image_name"
    command: "your_command"
    volumes:
      - name: "data_volume"
        path: "/data/input"
