name: Platform Start

envs:
  - BEAGLE_WIND_ROOT
  - BEAGLE_WIND_PASSWD
  - BEAGLE_WIND_TURN_HOST
  - BEAGLE_WIND_TURN_PORT
  - BEAGLE_WIND_TURN_PROTOCOL
  - BEAGLE_WIND_TURN_USERNAME
  - BEAGLE_WIND_TURN_PASSWORD
  - S3_ACCESS_KEY
  - S3_SECRET_KEY
  - S3_BUCKET
  - S3_URL

args:
  - PLATFORM
  - INSTANCE
  - IMAGE
  - PORT
  - HOSTNAME

steps:
  - name: minio
    container:
      image: registry.cn-qingdao.aliyuncs.com/wod/devops-minio:1.0
      volumes:
        - "${{ envs.BEAGLE_WIND_ROOT }}:/data/wind"
      command:
        - mkdir -p /data/wind/platforms
        - mc alias set cache --api=S3v4 ${{ envs.S3_URL }} ${{ envs.S3_ACCESS_KEY }} ${{ envs.S3_SECRET_KEY }}
        - mc cp cache/${{ envs.S3_BUCKET }}/platforms/${{ args.PLATFORM }}.tar.gz /data/wind/platforms/${{ args.PLATFORM }}.tar.gz

  - name: tgz
    container:
      image: registry.cn-qingdao.aliyuncs.com/wod/alpine:3
      volumes:
        - "${{ envs.BEAGLE_WIND_ROOT }}:/data/wind"
      command:
        - mkdir -p /data/wind/volumes
        - tar -xvzf /data/wind/platforms/${{ args.PLATFORM }}.tar.gz -C /data/wind/volumes/${{ args.INSTANCE }}

  - name: game
    type: service
    container:
      image: ${{ args.IMAGE }}
      container_name: ${{ args.INSTANCE }}
      hostname: ${{ args.HOSTNAME }}
      privileged: true
      deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
      security_opt:
        - seccomp=unconfined
      cap_add:
        - SYS_RAWIO
      tmpfs:
        - /dev/shm:rw
      devices:
        - /dev/dri:/dev/dri
      volumes:
        - /dev/input:/dev/input
        - /data/nvidia:/data/nvidia
        - ${{ envs.BEAGLE_WIND_ROOT }}/volumes/${{ args.INSTANCE }}/system:/home/ubuntu
      ports:
        - "${{ args.PORT }}:8080"
      environment:
        TZ: "Asia/Shanghai"
        DISPLAY_SIZEW: 1920
        DISPLAY_SIZEH: 1080
        DISPLAY_REFRESH: 60
        DISPLAY_DPI: 96
        DISPLAY_CDEPTH: 24
        SELKIES_ENCODER: nvh264enc
        SELKIES_VIDEO_BITRATE: 1000
        SELKIES_FRAMERATE: 30
        SELKIES_AUDIO_BITRATE: 24000
        SELKIES_ENABLE_RESIZE: "false"
        BEAGLE_ENABLE_DEBUG: "true"
        PASSWD: ${{ envs.BEAGLE_WIND_PASSWD }}
        SELKIES_BASIC_AUTH_PASSWORD: ${{ envs.BEAGLE_WIND_PASSWD }}
        SELKIES_ENABLE_HTTPS: "false"
        SELKIES_TURN_HOST: ${{ envs.BEAGLE_WIND_TURN_HOST }}
        SELKIES_TURN_PORT: ${{ envs.BEAGLE_WIND_TURN_PORT }}
        SELKIES_TURN_PROTOCOL: ${{ envs.BEAGLE_WIND_TURN_PROTOCOL }}
        SELKIES_TURN_USERNAME: ${{ envs.BEAGLE_WIND_TURN_USERNAME }}
        SELKIES_TURN_PASSWORD: ${{ envs.BEAGLE_WIND_TURN_PASSWORD }}